<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Access_log extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Access_log_model');
        $this->load->library('pagination');
        $this->load->model('Parent_app_user_model');
           $this->load->model('User_model');
           if (!$this->User_model->auth_session()) {
            redirect('Login');
        }
    } 

    /*
     * Listing of access_log
     */
    function index()
    {
        $config["base_url"] = base_url() . "access_log/index";
        $config["total_rows"] = $this->Access_log_model->count();
        $config["per_page"] = 20;
        $config["uri_segment"] = 3;

        $config['full_tag_open'] = "<ul class='pagination'>";
        $config['full_tag_close'] = '</ul>';
        $config['num_tag_open'] = '<li>';
        $config['num_tag_close'] = '</li>';
        $config['cur_tag_open'] = '<li class="active"><a href="#">';
        $config['cur_tag_close'] = '</a></li>';
        $config['prev_tag_open'] = '<li>';
        $config['prev_tag_close'] = '</li>';
        $config['first_tag_open'] = '<li>';
        $config['first_tag_close'] = '</li>';
        $config['last_tag_open'] = '<li>';
        $config['last_tag_close'] = '</li>';



        $config['prev_link'] = '<i class="fa fa-long-arrow-left"></i>Previous Page';
        $config['prev_tag_open'] = '<li>';
        $config['prev_tag_close'] = '</li>';


        $config['next_link'] = 'Next Page<i class="fa fa-long-arrow-right"></i>';
        $config['next_tag_open'] = '<li>';
        $config['next_tag_close'] = '</li>';


        $this->pagination->initialize($config); 

        $page = ($this->uri->segment(3)) ? $this->uri->segment(3) : 0;
        $data['list_num'] = $page;
        $data1 = $this->Access_log_model->get_all_access_log($config["per_page"], $page); 
      for($j=0;$j<count($data1);$j++)
     {
       $alog_parent_id=$data1[$j]['alog_parent_id'];
       $Parent_name = $this->Parent_app_user_model->get_parent_app_user($alog_parent_id);
       $data1[$j]['alog_parent_id']=$Parent_name['parent_app_user_name'];
     }
       $data['access_log']=$data1;
     
        $data['links']=$this->pagination->create_links();
        $this->load->view('access_log/index',$data);
    }

    /*
     * Adding a new access_log
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'alog_parent_id' => $this->input->post('alog_parent_id'),
				'alog_device' => $this->input->post('alog_device'),
				'alog_model' => $this->input->post('alog_model'),
				'alog_os_version' => $this->input->post('alog_os_version'),
				'alog_ip_address' => $this->input->post('alog_ip_address'),
				'alog_country' => $this->input->post('alog_country'),
				'alog_time_zone' => $this->input->post('alog_time_zone'),
				'alog_updated_time' => $this->input->post('alog_updated_time'),
				'alog_status' => $this->input->post('alog_status'),
				'alog_delete' => $this->input->post('alog_delete'),
            );
            
            $access_log_id = $this->Access_log_model->add_access_log($params);
            redirect('access_log/index');
        }
        else
        {            
             $this->load->view('access_log/add',$data);
        }
    }  

    /*
     * Editing a access_log
     */
    function edit($alog_id)
    {   
        // check if the access_log exists before trying to edit it
        $data['access_log'] = $this->Access_log_model->get_access_log($alog_id);
        
        if(isset($data['access_log']['alog_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'alog_parent_id' => $this->input->post('alog_parent_id'),
					'alog_device' => $this->input->post('alog_device'),
					'alog_model' => $this->input->post('alog_model'),
					'alog_os_version' => $this->input->post('alog_os_version'),
					'alog_ip_address' => $this->input->post('alog_ip_address'),
					'alog_country' => $this->input->post('alog_country'),
					'alog_time_zone' => $this->input->post('alog_time_zone'),
					'alog_updated_time' => $this->input->post('alog_updated_time'),
					'alog_status' => $this->input->post('alog_status'),
					'alog_delete' => $this->input->post('alog_delete'),
                );

                $this->Access_log_model->update_access_log($alog_id,$params);            
                redirect('access_log/index');
            }
            else
            {
                $this->load->view('access_log/edit',$data);
            }
        }
        else
            show_error('The access_log you are trying to edit does not exist.');
    } 

    /*
     * Deleting access_log
     */
    function remove($alog_id)
    {
        $access_log = $this->Access_log_model->get_access_log($alog_id);

        // check if the access_log exists before trying to delete it
        if(isset($access_log['alog_id']))
        {
            $this->Access_log_model->delete_access_log($alog_id);
            redirect('access_log/index');
        }
        else
            show_error('The access_log you are trying to delete does not exist.');
    }
    
}
