<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Attendance extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Attendance_model');
        $this->load->library('pagination');
           $this->load->model('User_model');
           if (!$this->User_model->auth_session()) {
            redirect('Login');
        }
    } 

    /*
     * Listing of attendance
     */
    function index($offset=0)
    {
         $data['page_title'] = 'Attendance';
         
         //pagination----------------------
        
        $config = array();
        $config["base_url"] = base_url() . "attendance/index";
        $config["total_rows"] = $this->Attendance_model->count();
        $config["per_page"] = 10;
        $config["uri_segment"] = 3;

          $config['full_tag_open'] = "<ul class='pagination'>";
    $config['full_tag_close'] = '</ul>';
    $config['num_tag_open'] = '<li>';
    $config['num_tag_close'] = '</li>';
    $config['cur_tag_open'] = '<li class="active"><a href="#">';
    $config['cur_tag_close'] = '</a></li>';
    $config['prev_tag_open'] = '<li>';
    $config['prev_tag_close'] = '</li>';
    $config['first_tag_open'] = '<li>';
    $config['first_tag_close'] = '</li>';
    $config['last_tag_open'] = '<li>';
    $config['last_tag_close'] = '</li>';



    $config['prev_link'] = '<i class="fa fa-long-arrow-left"></i>Previous Page';
    $config['prev_tag_open'] = '<li>';
    $config['prev_tag_close'] = '</li>';


    $config['next_link'] = 'Next Page<i class="fa fa-long-arrow-right"></i>';
    $config['next_tag_open'] = '<li>';
    $config['next_tag_close'] = '</li>';
    $this->pagination->initialize($config); 

        $page = ($this->uri->segment(3)) ? $this->uri->segment(3) : 0;
        $data['list_num'] = $page;
         $data['attendance'] = $this->Attendance_model->get_all_attendance($config["per_page"], $page); 
         $data['links']=$this->pagination->create_links();
         
         
         
         
         
        //--------------------------
         
//         
//        $data['attendance'] = $this->Attendance_model->get_all_attendance();

        $this->load->view('attendance/index',$data);
    }

    
      /*
     * Listing of attendance
     */

    /*
     * Adding a new attendance
     */
    function add()
    {   
         $data['page_title'] = 'Add Attendance';
        $this->load->library('form_validation');

		$this->form_validation->set_rules('at_child_id','At Child Id','required');
		$this->form_validation->set_rules('at_trip_id','At Trip Id','required');
		$this->form_validation->set_rules('at_time_stamp','At Time Stamp','required');
		$this->form_validation->set_rules('at_time_stamp_device','At Time Stamp Device','required');
		$this->form_validation->set_rules('at_loc_lati','At Loc Lati','required');
		$this->form_validation->set_rules('at_loc_longi','At Loc Longi','required');
		$this->form_validation->set_rules('at_loc_data_type','At Loc Data Type','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'at_child_id' => $this->input->post('at_child_id'),
				'at_trip_id' => $this->input->post('at_trip_id'),
				'at_time_stamp' => $this->input->post('at_time_stamp'),
				'at_time_stamp_device' => $this->input->post('at_time_stamp_device'),
				'at_loc_lati' => $this->input->post('at_loc_lati'),
				'at_loc_longi' => $this->input->post('at_loc_longi'),
				'at_loc_data_type' => $this->input->post('at_loc_data_type'),
            );
            
            $attendance_id = $this->Attendance_model->add_attendance($params);
            redirect('attendance/index',$data);
        }
        else
        {
            $this->load->view('attendance/add',$data);
        }
    }  

    /*
     * Editing a attendance
     */
    function edit($at_id)
    {   
        $data['page_title'] = 'Edit Attendance';
        // check if the attendance exists before trying to edit it
        $attendance = $this->Attendance_model->get_attendance($at_id);
        
        if(isset($attendance['at_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('at_child_id','At Child Id','required');
			$this->form_validation->set_rules('at_trip_id','At Trip Id','required');
			$this->form_validation->set_rules('at_time_stamp','At Time Stamp','required');
			$this->form_validation->set_rules('at_time_stamp_device','At Time Stamp Device','required');
			$this->form_validation->set_rules('at_loc_lati','At Loc Lati','required');
			$this->form_validation->set_rules('at_loc_longi','At Loc Longi','required');
			$this->form_validation->set_rules('at_loc_data_type','At Loc Data Type','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'at_child_id' => $this->input->post('at_child_id'),
					'at_trip_id' => $this->input->post('at_trip_id'),
					'at_time_stamp' => $this->input->post('at_time_stamp'),
					'at_time_stamp_device' => $this->input->post('at_time_stamp_device'),
					'at_loc_lati' => $this->input->post('at_loc_lati'),
					'at_loc_longi' => $this->input->post('at_loc_longi'),
					'at_loc_data_type' => $this->input->post('at_loc_data_type'),
                );

                $this->Attendance_model->update_attendance($at_id,$params);            
                redirect('attendance/index');
            }
            else
            {   
                $data['attendance'] = $this->Attendance_model->get_attendance($at_id);
    
                $this->load->view('attendance/edit',$data);
            }
        }
        else
            show_error('The attendance you are trying to edit does not exist.');
    } 

    /*
     * Deleting attendance
     */
    function remove($at_id)
    {
         $data['page_title'] = 'Delete Attendance';
        $attendance = $this->Attendance_model->get_attendance($at_id);

        // check if the attendance exists before trying to delete it
        if(isset($attendance['at_id']))
        {
            $this->Attendance_model->delete_attendance($at_id);
            redirect('attendance/index');
        }
        else
            show_error('The attendance you are trying to delete does not exist.');
    }
    

 
}
