<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Attendance_device extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Attendance_device_model');
        $this->load->library('pagination');
           $this->load->model('User_model');
           if (!$this->User_model->auth_session()) {
            redirect('Login');
        }
    } 

    /*
     * Listing of attendance_device
     */
    function index()
    {
         $data['page_title'] = 'Device Attendance';
        $config = array();
        $config["base_url"] = base_url() . "attendance_device/index";
        $config["total_rows"] = $this->Attendance_device_model->get_all_attendance_device_count();
        $config["per_page"] = 30;
        $config["uri_segment"] = 3;
        $config['full_tag_open'] = "<ul class='pagination'>";
        $config['full_tag_close'] = '</ul>';
        $config['num_tag_open'] = '<li>';
        $config['num_tag_close'] = '</li>';
        $config['cur_tag_open'] = '<li class="active"><a href="#">';
        $config['cur_tag_close'] = '</a></li>';
        $config['prev_tag_open'] = '<li>';
        $config['prev_tag_close'] = '</li>';
        $config['first_tag_open'] = '<li>';
        $config['first_tag_close'] = '</li>';
        $config['last_tag_open'] = '<li>';
        $config['last_tag_close'] = '</li>';



        $config['prev_link'] = '<i class="fa fa-long-arrow-left"></i>Previous Page';
        $config['prev_tag_open'] = '<li>';
        $config['prev_tag_close'] = '</li>';


        $config['next_link'] = 'Next Page<i class="fa fa-long-arrow-right"></i>';
        $config['next_tag_open'] = '<li>';
        $config['next_tag_close'] = '</li>';


         $this->pagination->initialize($config);
         $page = ($this->uri->segment(3)) ? $this->uri->segment(3) : 0;
         $data['attendance_device'] = $this->Attendance_device_model->get_all_attendance_device($config["per_page"], $page);
         $this->load->view('attendance_device/index', $data);
    }

    /*
     * Adding a new attendance_device
     */
    function add()
    {   
         $data['page_title'] = 'Device Attendance';
        $this->load->library('form_validation');

		$this->form_validation->set_rules('device_name','Device Name','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'device_name' => $this->input->post('device_name'),
				'device_desc' => $this->input->post('device_desc'),
//				'device_status' => $this->input->post('device_status'),
//				'device_delete' => $this->input->post('device_delete'),
//				'device_running_satus' => $this->input->post('device_running_satus'),
				'device_keeper' => $this->input->post('device_keeper'),
				'device_keeper_phone' => $this->input->post('device_keeper_phone'),
            );
            
            $attendance_device_id = $this->Attendance_device_model->add_attendance_device($params);
            redirect('attendance_device/index');
        }
        else
        {  
         $this->load->view('attendance_device/add', $data);
        }
    }  

    /*
     * Editing a attendance_device
     */
    function edit($device_id)
    {   
         $data['page_title'] = 'Device Attendance';
        // check if the attendance_device exists before trying to edit it
        $data['attendance_device'] = $this->Attendance_device_model->get_attendance_device($device_id);
        
        if(isset($data['attendance_device']['device_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('device_name','Device Name','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'device_name' => $this->input->post('device_name'),
					'device_desc' => $this->input->post('device_desc'),
//					'device_status' => $this->input->post('device_status'),
//					'device_delete' => $this->input->post('device_delete'),
//					'device_running_satus' => $this->input->post('device_running_satus'),
					'device_keeper' => $this->input->post('device_keeper'),
					'device_keeper_phone' => $this->input->post('device_keeper_phone'),
                );

                $this->Attendance_device_model->update_attendance_device($device_id,$params);            
                redirect('attendance_device/index');
            }
            else
            {
                $this->load->view('attendance_device/edit', $data);
            }
        }
        else
            show_error('The attendance_device you are trying to edit does not exist.');
    } 

    /*
     * Deleting attendance_device
     */
    function remove($device_id)
    {
        $attendance_device = $this->Attendance_device_model->get_attendance_device($device_id);

        // check if the attendance_device exists before trying to delete it
        if(isset($attendance_device['device_id']))
        {
            $this->Attendance_device_model->delete_attendance_device($device_id);
            redirect('attendance_device/index');
        }
        else
            show_error('The attendance_device you are trying to delete does not exist.');
    }
    
}
