<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Bus extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bu_model');
        $this->load->model('User_model');
         $this->load->model('Bus_app_user_model');
         $this->load->model('Setting_model');
       if(!$this->User_model->auth_session()){
            redirect('Login');
       }
    } 

    /*
     * Listing of bus
     */
    function index()
    {
         $data['page_title'] = 'Bus';
        $data['bus'] = $this->Bu_model->get_all_bus();

        $this->load->view('bus/index',$data); 
    }

    /*
     * Adding a new bu
     */
    function add()
    {   
         $data['page_title'] = 'Bus Adding';
        $this->load->library('form_validation');

		$this->form_validation->set_rules('bus_name','Bus Name','required|numeric');
                $this->form_validation->set_rules('bus_desc','Bus Description','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'bus_name' => $this->input->post('bus_name'),
				'bus_desc' => $this->input->post('bus_desc'),
                                'driver_name' => $this->input->post('driver_name'),
				'driver_assistant' => $this->input->post('driver_assistant'),
                                'driver_phone' => $this->input->post('driver_phone'),
				'bus_status' => $this->input->post('bus_status'),
                                'assistant_phone' => $this->input->post('assistant_phone'),
            );
            
            $bu_id = $this->Bu_model->add_bu($params);
            redirect('bus/index');
        }
        else
        {
            $this->load->view('bus/add',$data);
        }
    }  

    /*
     * Editing a bu
     */
    function edit($bus_id)
    {   
         $data['page_title'] = 'Bus Editing';
        // check if the bu exists before trying to edit it
        $bu = $this->Bu_model->get_bu($bus_id);
        
        if(isset($bu['bus_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('bus_name','Bus Name','required|numeric');
                $this->form_validation->set_rules('bus_desc','Bus Description','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'bus_name' => $this->input->post('bus_name'),
					'bus_desc' => $this->input->post('bus_desc'),
                                    'driver_name' => $this->input->post('driver_name'),
				'driver_assistant' => $this->input->post('driver_assistant'),
                                'driver_phone' => $this->input->post('driver_phone'),
                                'bus_status' => $this->input->post('bus_status'),
                    'assistant_phone' => $this->input->post('assistant_phone'),
					
                );

                $this->Bu_model->update_bu($bus_id,$params);            
                redirect('bus/index');
            }
            else
            {   
                $data['bu'] = $this->Bu_model->get_bu($bus_id);
    
                $this->load->view('bus/edit',$data);
            }
        }
        else
            show_error('The bu you are trying to edit does not exist.');
    } 

    /*
     * Deleting bu
     */
    function remove($bus_id)
    {
         $data['page_title'] = 'Bus Deleting';
        $bu = $this->Bu_model->get_bu($bus_id);

        // check if the bu exists before trying to delete it
        if(isset($bu['bus_id']))
        {
            $this->Bu_model->delete_bu($bus_id);
            redirect('bus/index');
        }
        else
            show_error('The bu you are trying to delete does not exist.');
    }
    
    
     function change_status()
    {
      $bus_id =  $this->uri->segment(3);
      $bus_status =  $this->uri->segment(4);
         if($bus_status==0)
         {
             $status=1;
         }
         else
         {
             $status=0;
         }
      // echo $status;
        // check if the child exists before trying to update it
        if($bus_id)
        {
           $this->Bu_model->status_bus($bus_id,$status);
             redirect('bus/index');
        }
        else
            show_error('The child you are trying to delete does not exist.');
    } 
    
    /*
     * Adding csv
     */
    function add_csv()
    {   
        $data['page_title'] = 'Bus Adding';
        if(isset($_POST['submit'])){
          if($_FILES['csv']['tmp_name']==''){
                 $this->session->set_flashdata('error', 'Please select CSV file');
                 redirect('bus/add_csv', $data);
            }
   if (($handle = fopen($_FILES['csv']['tmp_name'], "r")) !== FALSE) {
         fgetcsv($handle); 
        $settings = $this->Setting_model->get_all_settings();
        $is_truncate='No';
        foreach ($settings as $key => $value) {
              $is_truncate = $value['truncate'];
               }
       if($is_truncate=='Yes'){     
       $truncate  = $this->Bu_model->truncate_bus();
        $truncate_bus_app  = $this->Bus_app_user_model->truncate_bus_app_users();              
       }
       
//       echo $this->db->last_query();
//      exit();
//       
         while (($data1 = fgetcsv($handle, 1000, ",")) !== FALSE) {
        $num = count($data1);
        for ($c=0; $c < $num; $c++) {
        $data[$c] = $data1[$c];            
       }
       $params = array(
               
					'bus_name' => trim($data['0']),
					'bus_desc' => trim($data['1']),
					'driver_name' => trim($data['2']),
					'driver_assistant' => trim($data['3']),
					'driver_phone' => trim($data['4']),
                                        'assistant_phone' => trim($data['5']),
					
                );
  
       
      $bus_last_id = $this->Bu_model->add_bu($params);
     
      $bus_app_params = array(
               
					'bus_app_user_name' => trim($data['1']),
					'bus_app_user_password' => '123',
					'bus_app_user_bus_id' => $bus_last_id,
		 );
           
       $bus_last_id = $this->Bus_app_user_model->add_bus_app_user($bus_app_params);
      
//      echo $this->db->last_query();
//      exit();
      }
       fclose($handle);
        redirect('bus/index',$data);
    }
    }
     $this->load->view('bus/add_csv',$data); 
    }
      
    
    
    
}
