<?php
/*
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */

class Child extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Child_model');
        $this->load->model('User_model');
        $this->load->model('common_model');
        $this->load->model('Bu_model');
        $this->load->model('Trip_model');
        $this->load->model('Setting_model');
        $this->load->library('pagination');
        $this->load->model('Parent_app_user_model');
        $this->load->model('Parent_child_mapping_model');
        
       
        if (!$this->User_model->auth_session()) {
            redirect('Login');
        }
    }

    /*
     * Listing of child
     */

    function index($offset = 0) {
        $data['page_title'] = 'Child';
        //$_GET['error']= '';
        $data['bus'] = $this->Bu_model->get_all_bus();
        $data['registration_number'] = $this->Child_model->get_all_child();
        //pagination----------------------

        $config = array();
        $config["base_url"] = base_url() . "child/index";
        $config["total_rows"] = $this->Child_model->count();
        $config["per_page"] = 10;
        $config["uri_segment"] = 3;

        $config['full_tag_open'] = "<ul class='pagination'>";
        $config['full_tag_close'] = '</ul>';
        $config['num_tag_open'] = '<li>';
        $config['num_tag_close'] = '</li>';
        $config['cur_tag_open'] = '<li class="active"><a href="#">';
        $config['cur_tag_close'] = '</a></li>';
        $config['prev_tag_open'] = '<li>';
        $config['prev_tag_close'] = '</li>';
        $config['first_tag_open'] = '<li>';
        $config['first_tag_close'] = '</li>';
        $config['last_tag_open'] = '<li>';
        $config['last_tag_close'] = '</li>';



        $config['prev_link'] = '<i class="fa fa-long-arrow-left"></i>Previous Page';
        $config['prev_tag_open'] = '<li>';
        $config['prev_tag_close'] = '</li>';


        $config['next_link'] = 'Next Page<i class="fa fa-long-arrow-right"></i>';
        $config['next_tag_open'] = '<li>';
        $config['next_tag_close'] = '</li>';


        $this->pagination->initialize($config);

        $page = ($this->uri->segment(3)) ? $this->uri->segment(3) : 0;

        $data1 = $this->Child_model->get_all_child_index($config["per_page"], $page);
        //  echo $this->db->last_query();

        for ($j = 0; $j < count($data1); $j++) {
            $child_bus_no_pickup = $data1[$j]['child_bus_no_pickup'];
            $bus_number = $this->Bu_model->get_bu($child_bus_no_pickup);
            $data1[$j]['child_bus_no_pickup'] = $bus_number['bus_desc'];

            $child_bus_no_drop_off = $data1[$j]['child_bus_no_drop_off'];
            $bus_number_off = $this->Bu_model->get_bu($child_bus_no_drop_off);
            $data1[$j]['child_bus_no_drop_off'] = $bus_number_off['bus_desc'];
            //trip
            $child_trip_no_drop_off = $data1[$j]['child_trip_no_drop_off'];
            $trip_number_off = $this->Trip_model->get_trip($child_trip_no_drop_off);
            $data1[$j]['child_trip_no_drop_off'] = $trip_number_off['trip_no'];

            $child_trip_no_pickup = $data1[$j]['child_trip_no_pickup'];
            $trip_number = $this->Trip_model->get_trip($child_trip_no_pickup);
            $data1[$j]['child_trip_no_pickup'] = $trip_number['trip_no'];
            
             $child_id = $data1[$j]['child_id'];
             $signed_status = $this->Parent_app_user_model->get_signedup_or_not($child_id);
             $data1[$j]['signed_status'] = $signed_status;
            
        }
      // print_r($data1);        exit();
        $data['child'] = $data1;
        $data['list_num'] = $page;
        $data['links'] = $this->pagination->create_links();





        //--------------------------
//        $data['child'] = $this->Child_model->get_all_child();

        $this->load->view('child/index', $data);
    }

    /*
     * Adding a new child
     */

    function add() {
        $data['page_title'] = 'Child Adding';
        $data['bus_pick_up'] = $this->Bu_model->get_bus_pickup('pickup');
//        echo $this->db->last_query();
        $data['bus_drop_off'] = $this->Bu_model->get_bus_dropoff('drop off');
        $this->load->library('form_validation');

        $this->form_validation->set_rules('child_name', 'Child Name', 'required|max_length[500]');
        $this->form_validation->set_rules('child_gender', 'Child Gender', 'required');
//		$this->form_validation->set_rules('child_photo','Child Photo','required');
        $this->form_validation->set_rules('child_class', 'Child Class', 'required|max_length[10]');
        $this->form_validation->set_rules('child_section', 'Child Section', 'required|max_length[15]');
        $this->form_validation->set_rules('child_teacher', 'Child Teacher', 'required|max_length[500]');
//        $this->form_validation->set_rules('child_bus_no_pickup', 'Child Bus No Pickup', 'required|integer');
//        $this->form_validation->set_rules('child_bus_no_drop_off', 'Child Bus No Drop Off', 'required|integer');
        
//        $this->form_validation->set_rules('child_drop_off_order', 'Child Drop Off Order', 'required|integer');
//        $this->form_validation->set_rules('child_pickup_order', 'Child Pickup Order', 'required|integer');
        $this->form_validation->set_rules('child_father_name', 'Child Father Name', 'required|max_length[500]');
//        $this->form_validation->set_rules('child_mother_name', 'Child Mother Name', 'required|max_length[500]');
        $this->form_validation->set_rules('child_father_tel', 'Child Father Tel', 'required');
//        $this->form_validation->set_rules('child_mother_tel', 'Child Mother Tel', 'required');
//        $this->form_validation->set_rules('child_home_tel', 'Child Home Tel', 'required');
        $this->form_validation->set_rules('child_father_email_id', 'Child Father Email Id', 'required|max_length[255]|valid_email');
//        $this->form_validation->set_rules('child_mother_email_id', 'Child Mother Email Id', 'required|max_length[255]|valid_email');
//        $this->form_validation->set_rules('child_blood_group', 'Child Blood Group', 'required|max_length[5]');
//        $this->form_validation->set_rules('child_address', 'Child Address', 'required');
//        $this->form_validation->set_rules('child_area', 'Child Area', 'required|max_length[500]');
//        $this->form_validation->set_rules('child_city', 'Child City', 'required|max_length[500]');
//        $this->form_validation->set_rules('child_pickup_lati', 'Child Pickup Lati', 'required|max_length[20]');
//        $this->form_validation->set_rules('child_pickup_longi', 'Child Pickup Longi', 'required|max_length[20]');
//        $this->form_validation->set_rules('child_drop_off_lati', 'Child Drop Off Lati', 'required|max_length[20]');
//        $this->form_validation->set_rules('child_drop_off_longi', 'Child Drop Off Longi', 'required|max_length[20]');
        $this->form_validation->set_rules('child_nfc_id', 'Child Nfc Id', 'required');
//        $this->form_validation->set_rules('child_sms', 'Child Sms', 'required');
//        $this->form_validation->set_rules('child_push_notification', 'Child Push Notification', 'required|max_length[10]');
//        $this->form_validation->set_rules('child_trip_no_pickup', 'Child Trip No Pickup', 'required|integer');
//        $this->form_validation->set_rules('child_trip_no_drop_off', 'Child Trip No Drop Off', 'required|integer');
//        $this->form_validation->set_rules('child_personal_transport_pickup', 'Child Personal Transport Pickup', 'required');
//        $this->form_validation->set_rules('child_personal_transport_drop_off', 'Child Personal Transport Drop Off', 'required');
//		$this->form_validation->set_rules('child_status','Child Status','required|integer');

        if ($this->form_validation->run()) {

            if(!empty($_FILES['child_photo']['name'])) {   
            $updated_time = date('Y-m-d-H-i-s');
            $ext = explode(".", $_FILES['child_photo']['name']);
            $real_name = 'std_' . date('Y-m-d-H-i-s') . '_' . uniqid() . '.' . $ext[1];
            //image upload
            $file_name = 'emp_' . date('Y-m-d-H-i-s') . '_' . uniqid();
            $config['file_name'] = $real_name;
            $config['upload_path'] = FCPATH . "uploads/std/";
            $config['allowed_types'] = 'gif|jpg|png';
            $config['max_size'] = '500';
            $config['max_width'] = '1024';
            $config['max_height'] = '768';
            $status_upload = $this->common_model->do_upload($config, 'child_photo');
            }
            $child_pickup_time=str_pad($this->input->post('pickup_hour'), 2, "0", STR_PAD_LEFT).':'.str_pad($this->input->post('pickup_minutes'), 2, "0", STR_PAD_LEFT);
            $child_dropoff_time=str_pad($this->input->post('dropoff_hour'), 2, "0", STR_PAD_LEFT).':'.str_pad($this->input->post('dropoff_minutes'), 2, "0", STR_PAD_LEFT);
            $params = array(
                'child_name' => $this->input->post('child_name'),
                'child_gender' => $this->input->post('child_gender'),
//                'child_photo' => $real_name,
                'child_class' => $this->input->post('child_class'),
                'child_section' => $this->input->post('child_section'),
                'child_teacher' => $this->input->post('child_teacher'),
                'child_bus_no_pickup' => $this->input->post('child_bus_no_pickup'),
                'child_bus_no_drop_off' => $this->input->post('child_bus_no_drop_off'),
//                'child_drop_off_order' => $this->input->post('child_drop_off_order'),
//                'child_pickup_order' => $this->input->post('child_pickup_order'),
                'child_father_name' => $this->input->post('child_father_name'),
//                'child_mother_name' => $this->input->post('child_mother_name'),
                'child_father_tel' => $this->input->post('child_father_tel'),
//                'child_mother_tel' => $this->input->post('child_mother_tel'),
//                'child_home_tel' => $this->input->post('child_home_tel'),
                'child_father_email_id' => $this->input->post('child_father_email_id'),
//                'child_mother_email_id' => $this->input->post('child_mother_email_id'),
//                'child_blood_group' => $this->input->post('child_blood_group'),
//                'child_address' => $this->input->post('child_address'),
//                'child_area' => $this->input->post('child_area'),
//                'child_city' => $this->input->post('child_city'),
//                'child_pickup_lati' => $this->input->post('child_pickup_lati'),
//                'child_pickup_longi' => $this->input->post('child_pickup_longi'),
//                'child_drop_off_lati' => $this->input->post('child_drop_off_lati'),
//                'child_drop_off_longi' => $this->input->post('child_drop_off_longi'),
                'child_nfc_id' => $this->input->post('child_nfc_id'),
//                'child_sms' => $this->input->post('child_sms'),
//                'child_push_notification' => $this->input->post('child_push_notification'),
                'child_trip_no_pickup' => $this->input->post('child_trip_no_pickup'),
                'child_trip_no_drop_off' => $this->input->post('child_trip_no_drop_off'),
//                'child_personal_transport_pickup' => $this->input->post('child_personal_transport_pickup'),
//                'child_personal_transport_drop_off' => $this->input->post('child_personal_transport_drop_off'),
//				'child_status' => $this->input->post('child_status'),
                'child_pickup_time' => $child_pickup_time,
                'child_dropoff_time' => $child_dropoff_time,
                'child_handicapped_type' => $this->input->post('child_handicapped_type'),
                'child_reg_no' => $this->input->post('child_reg_no'),
            );



            $parent_app_user_id_exist = $this->Parent_app_user_model->check_parent_email($this->input->post('child_father_email_id'));
            if ($parent_app_user_id_exist) {
                $parent_app_user_id = $parent_app_user_id_exist;
            } else {
                $user_name = $this->input->post('child_father_email_id');
                $number_of_digits = 4;
                $pin_number = substr(number_format(time() * mt_rand(), 0, '', ''), 0, $number_of_digits);
                $params_parent_app = array(
                    'parent_app_user_name' => $user_name,
                    'parent_app_user_password' => '123',
                    'parent_app_user_status' => '1',
                    'pin_number' => $pin_number,
                );

                $parent_app_user_id = $this->Parent_app_user_model->add_parent_app_user($params_parent_app);
            }
            // print_r($parent_app_user_id);
//          



            $child_last_id = $this->Child_model->add_child($params);


            $parent_child_mapping = array(
                'parent_id' => $parent_app_user_id,
                'child_id' => $child_last_id,
            );

            $parent_child_mapping_id = $this->Parent_child_mapping_model->add_parent_child_mapping($parent_child_mapping);

            redirect('child/index');
        } else {
            $this->load->view('child/add', $data);
        }
    }

    /*
     * Editing a child
     */

    function edit($child_id) {
        $data['page_title'] = 'Child Editing';
       // $data['error']='';
        $data['bus_pick_up'] = $this->Bu_model->get_bus_pickup('pickup');
//        echo $this->db->last_query();
        $data['bus_drop_off'] = $this->Bu_model->get_bus_dropoff('drop off');
        //  echo $this->db->last_query();
        // check if the child exists before trying to edit it
        $child = $this->Child_model->get_child($child_id);

        $data['up'] = $this->Trip_model->get_trip_with_bus_id_index($child['child_bus_no_pickup']);
        // echo $this->db->last_query();
        $data['drop'] = $this->Trip_model->get_trip_with_bus_id_index($child['child_bus_no_drop_off']);
        
        
        $child_pickup_time=str_pad($this->input->post('pickup_hour'), 2, "0", STR_PAD_LEFT).':'.str_pad($this->input->post('pickup_minutes'), 2, "0", STR_PAD_LEFT);
        $child_dropoff_time=str_pad($this->input->post('dropoff_hour'), 2, "0", STR_PAD_LEFT).':'.str_pad($this->input->post('dropoff_minutes'), 2, "0", STR_PAD_LEFT);
         $data['list_num'] = $this->uri->segment(4);
        //echo $this->db->last_query();
        if (isset($child['child_id'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('child_name', 'Child Name', 'required|max_length[500]');
            $this->form_validation->set_rules('child_gender', 'Child Gender', 'required');
//			$this->form_validation->set_rules('child_photo','Child Photo','required');
            $this->form_validation->set_rules('child_class', 'Child Class', 'required|max_length[10]');
            $this->form_validation->set_rules('child_section', 'Child Section', 'required|max_length[15]');
            $this->form_validation->set_rules('child_teacher', 'Child Teacher', 'required|max_length[500]');
//            $this->form_validation->set_rules('child_bus_no_pickup', 'Child Bus No Pickup', 'required|integer');
//            $this->form_validation->set_rules('child_bus_no_drop_off', 'Child Bus No Drop Off', 'required|integer');
//            $this->form_validation->set_rules('child_drop_off_order', 'Child Drop Off Order', 'required|integer');
//            $this->form_validation->set_rules('child_pickup_order', 'Child Pickup Order', 'required|integer');
            $this->form_validation->set_rules('child_father_name', 'Child Father Name', 'required|max_length[500]');
//            $this->form_validation->set_rules('child_mother_name', 'Child Mother Name', 'required|max_length[500]');
            $this->form_validation->set_rules('child_father_tel', 'Child Father Tel', 'required');
//            $this->form_validation->set_rules('child_mother_tel', 'Child Mother Tel', 'required');
//            $this->form_validation->set_rules('child_home_tel', 'Child Home Tel', 'required');
            $this->form_validation->set_rules('child_father_email_id', 'Child Father Email Id', 'required|max_length[255]|valid_email');
//            $this->form_validation->set_rules('child_mother_email_id', 'Child Mother Email Id', 'required|max_length[255]|valid_email');
//            $this->form_validation->set_rules('child_blood_group', 'Child Blood Group', 'required|max_length[5]');
//            $this->form_validation->set_rules('child_address', 'Child Address', 'required');
//            $this->form_validation->set_rules('child_area', 'Child Area', 'required|max_length[500]');
//            $this->form_validation->set_rules('child_city', 'Child City', 'required|max_length[500]');
//            $this->form_validation->set_rules('child_pickup_lati', 'Child Pickup Lati', 'required|max_length[20]');
//            $this->form_validation->set_rules('child_pickup_longi', 'Child Pickup Longi', 'required|max_length[20]');
//            $this->form_validation->set_rules('child_drop_off_lati', 'Child Drop Off Lati', 'required|max_length[20]');
//            $this->form_validation->set_rules('child_drop_off_longi', 'Child Drop Off Longi', 'required|max_length[20]');
            $this->form_validation->set_rules('child_nfc_id', 'Child Nfc Id', 'required');
//            $this->form_validation->set_rules('child_sms', 'Child Sms', 'required');
//            $this->form_validation->set_rules('child_push_notification', 'Child Push Notification', 'required|max_length[10]');
//            $this->form_validation->set_rules('child_trip_no_pickup', 'Child Trip No Pickup', 'required|integer');
//            $this->form_validation->set_rules('child_trip_no_drop_off', 'Child Trip No Drop Off', 'required|integer');
//            $this->form_validation->set_rules('child_personal_transport_pickup', 'Child Personal Transport Pickup', 'required');
//            $this->form_validation->set_rules('child_personal_transport_drop_off', 'Child Personal Transport Drop Off', 'required');
//			$this->form_validation->set_rules('child_status','Child Status','required|integer');

            if ($this->form_validation->run()) {
                if (!empty($_FILES['child_photo']['name'])) {

                    $updated_time = date('Y-m-d-H-i-s');
                    $ext = explode(".", $_FILES['child_photo']['name']);
                    $real_name = 'std_' . date('Y-m-d-H-i-s') . '_' . uniqid() . '.' . $ext[1];
                    //image upload
                    $file_name = 'emp_' . date('Y-m-d-H-i-s') . '_' . uniqid();
                    $config['file_name'] = $real_name;
                    $config['upload_path'] = FCPATH . "uploads/std/";
                    $config['allowed_types'] = 'gif|jpg|png';
                    $config['max_size'] = '500';
                    $config['max_width'] = '1024';
                    $config['max_height'] = '768';
                    $status_upload = $this->common_model->do_upload($config, 'child_photo');
                    $params = array(
                        'child_name' => $this->input->post('child_name'),
                        'child_gender' => $this->input->post('child_gender'),
                        'child_photo' => $real_name,
                        'child_class' => $this->input->post('child_class'),
                        'child_section' => $this->input->post('child_section'),
                        'child_teacher' => $this->input->post('child_teacher'),
                        'child_bus_no_pickup' => $this->input->post('child_bus_no_pickup'),
                        'child_bus_no_drop_off' => $this->input->post('child_bus_no_drop_off'),
                        'child_drop_off_order' => $this->input->post('child_drop_off_order'),
                        'child_pickup_order' => $this->input->post('child_pickup_order'),
                        'child_father_name' => $this->input->post('child_father_name'),
                        'child_mother_name' => $this->input->post('child_mother_name'),
                        'child_father_tel' => $this->input->post('child_father_tel'),
                        'child_mother_tel' => $this->input->post('child_mother_tel'),
                        'child_home_tel' => $this->input->post('child_home_tel'),
                        'child_father_email_id' => $this->input->post('child_father_email_id'),
                        'child_mother_email_id' => $this->input->post('child_mother_email_id'),
                        'child_blood_group' => $this->input->post('child_blood_group'),
                        'child_address' => $this->input->post('child_address'),
                        'child_area' => $this->input->post('child_area'),
                        'child_city' => $this->input->post('child_city'),
                        'child_pickup_lati' => $this->input->post('child_pickup_lati'),
                        'child_pickup_longi' => $this->input->post('child_pickup_longi'),
                        'child_drop_off_lati' => $this->input->post('child_drop_off_lati'),
                        'child_drop_off_longi' => $this->input->post('child_drop_off_longi'),
                        'child_nfc_id' => $this->input->post('child_nfc_id'),
                        'child_sms' => $this->input->post('child_sms'),
                        'child_push_notification' => $this->input->post('child_push_notification'),
                        'child_trip_no_pickup' => $this->input->post('child_trip_no_pickup'),
                        'child_trip_no_drop_off' => $this->input->post('child_trip_no_drop_off'),
                        'child_personal_transport_pickup' => $this->input->post('child_personal_transport_pickup'),
                        'child_personal_transport_drop_off' => $this->input->post('child_personal_transport_drop_off'),
                         'child_pickup_time' => $child_pickup_time,
                'child_dropoff_time' => $child_dropoff_time,
                'child_handicapped_type' => $this->input->post('child_handicapped_type'),
//					'child_status' => $this->input->post('child_status'),
                        'child_reg_no' => $this->input->post('child_reg_no'),
                    );
                } else {
                    $params = array(
                        'child_name' => $this->input->post('child_name'),
                        'child_gender' => $this->input->post('child_gender'),
                        'child_class' => $this->input->post('child_class'),
                        'child_section' => $this->input->post('child_section'),
                        'child_teacher' => $this->input->post('child_teacher'),
                        'child_bus_no_pickup' => $this->input->post('child_bus_no_pickup'),
                        'child_bus_no_drop_off' => $this->input->post('child_bus_no_drop_off'),
                        'child_drop_off_order' => $this->input->post('child_drop_off_order'),
                        'child_pickup_order' => $this->input->post('child_pickup_order'),
                        'child_father_name' => $this->input->post('child_father_name'),
                        'child_mother_name' => $this->input->post('child_mother_name'),
                        'child_father_tel' => $this->input->post('child_father_tel'),
                        'child_mother_tel' => $this->input->post('child_mother_tel'),
                        'child_home_tel' => $this->input->post('child_home_tel'),
                        'child_father_email_id' => $this->input->post('child_father_email_id'),
                        'child_mother_email_id' => $this->input->post('child_mother_email_id'),
                        'child_blood_group' => $this->input->post('child_blood_group'),
                        'child_address' => $this->input->post('child_address'),
                        'child_area' => $this->input->post('child_area'),
                        'child_city' => $this->input->post('child_city'),
                        'child_pickup_lati' => $this->input->post('child_pickup_lati'),
                        'child_pickup_longi' => $this->input->post('child_pickup_longi'),
                        'child_drop_off_lati' => $this->input->post('child_drop_off_lati'),
                        'child_drop_off_longi' => $this->input->post('child_drop_off_longi'),
                        'child_nfc_id' => $this->input->post('child_nfc_id'),
                        'child_sms' => $this->input->post('child_sms'),
                        'child_push_notification' => $this->input->post('child_push_notification'),
                        'child_trip_no_pickup' => $this->input->post('child_trip_no_pickup'),
                        'child_trip_no_drop_off' => $this->input->post('child_trip_no_drop_off'),
                        'child_personal_transport_pickup' => $this->input->post('child_personal_transport_pickup'),
                        'child_personal_transport_drop_off' => $this->input->post('child_personal_transport_drop_off'),
                         'child_pickup_time' => $child_pickup_time,
                'child_dropoff_time' => $child_dropoff_time,
                'child_handicapped_type' => $this->input->post('child_handicapped_type'),
//					'child_status' => $this->input->post('child_status'),
                        'child_reg_no' => $this->input->post('child_reg_no'),
                    );
                }
                $this->Child_model->update_child($child_id, $params);
                // echo $this->db->last_query();exit();
                if(($this->input->post('pickup')) || ($this->input->post('dropoff')) || ($this->input->post('registration')))
                {
                redirect('child/search?pickup='.$this->input->post('pickup').'&dropoff='.$this->input->post('dropoff').'&registration='.$this->input->post('registration'), $data); 
                }
                else
                {
                    redirect('child/index/'.$this->input->post('list_num'));
                }
            } else {
                $data['child'] = $this->Child_model->get_child($child_id);

                $this->load->view('child/edit', $data);
            }
        } else
            show_error('The child you are trying to edit does not exist.');
    }

    /*
     * Deleting child
     */

    function remove($child_id) {
        $data['page_title'] = 'Child Deleting';
         $list_num = $this->uri->segment(4); 
        $child = $this->Child_model->get_child($child_id);

        // check if the child exists before trying to delete it
        if (isset($child['child_id'])) {
            $this->Child_model->delete_child($child_id);
            redirect('child/index/'.$list_num);
        } else
            show_error('The child you are trying to delete does not exist.');
    }

    /*
     * status child
     */

    function change_status($child_id) {
        $child_id = $this->uri->segment(3);
        $status = $this->uri->segment(4);
         $list_num = $this->uri->segment(5);
        if ($status == 0) {
            $child_status = 1;
        } else {
            $child_status = 0;
        }
        // check if the child exists before trying to update it
        if ($child_id) {
            $this->Child_model->status_child($child_id, $child_status);
            redirect('child/index/'.$list_num);
        } else
            show_error('The child you are trying to delete does not exist.');
    }

    function trip_list($id) {
        $data['trip_num'] = $this->Trip_model->get_trip_with_bus_id_index($id);
        // echo $this->db->last_query();
        $this->load->view('child/get_trip_num', $data);
    }

    /*
     * Adding a new child
     */

    function add_csv() {
        $data['page_title'] = 'Child add';
        $settings = $this->Setting_model->get_all_settings();
        $auth_code='123';
        foreach ($settings as $key => $value) {
            
             $auth_code=$value['set_auth_code'];
          }
        if (isset($_POST['submit'])) {

            if($_FILES['csv']['tmp_name']==''){
                 $this->session->set_flashdata('error', 'Please select CSV file');
                 redirect('child/add_csv', $data);
            }
            
            if (($handle = fopen($_FILES['csv']['tmp_name'], "r")) !== FALSE) {
                fgetcsv($handle);
                $settings = $this->Setting_model->get_all_settings();
                 $is_truncate='No';
                 foreach ($settings as $key => $value) {
                       $is_truncate = $value['truncate'];
                        }
                        
                        
                        
                if($is_truncate=='Yes'){     
                $truncate = $this->Child_model->truncate_child();
                $truncate1 = $this->Parent_app_user_model->truncate_Parent_app_user();
                $truncate2 = $this->Parent_child_mapping_model->truncate_Parent_child_mapping();                    
                }else {
                  $this->session->set_flashdata('error', 'Please change setting for truncate child list in settings page for clearing db');
                 redirect('child/add_csv', $data);
                }
                while (($data1 = fgetcsv($handle, 1000, ",")) !== FALSE) {
                    $num = count($data1);
                    for ($c = 0; $c < $num; $c++) {
                        $data[$c] = $data1[$c];
                    }

                    $bus_id_pickup = $this->Bu_model->get_bus_id_by_desc(trim($data['6']));
                    $bus_id_pickup=($bus_id_pickup)?$bus_id_pickup['bus_id']:'0';
                    $trip_id_pickup = $this->Trip_model->get_trip_id(trim($data['7']));
                    $trip_id_pickup=($trip_id_pickup)?$trip_id_pickup['trip_id']:'0';
                    $bus_id_drop_off = $this->Bu_model->get_bus_id_by_desc(trim($data['8']));
                    $bus_id_drop_off=($bus_id_drop_off)?$bus_id_drop_off['bus_id']:'0';
                    $trip_id_drop_off = $this->Trip_model->get_trip_id(trim($data['9']));
                    $trip_id_drop_off=($trip_id_drop_off)?$trip_id_drop_off['trip_id']:'0';
                    $params = array(
                        'child_name' => trim($data['0']),
                        'child_gender' => trim($data['1']),
                        'child_photo' => trim($data['2']),
                        'child_class' => trim($data['3']),
                        'child_section' => trim($data['4']),
                        'child_teacher' => trim($data['5']),
                        'child_bus_no_pickup' => $bus_id_pickup,
                        'child_bus_no_drop_off' => $bus_id_drop_off,
                        'child_drop_off_order' => trim($data['10']),
                        'child_pickup_order' => trim($data['11']),
                        'child_father_name' => trim($data['12']),
                        'child_mother_name' => trim($data['13']),
                        'child_father_tel' => trim($data['14']),
                        'child_mother_tel' => trim($data['15']),
                        'child_home_tel' => trim($data['16']),
                        'child_father_email_id' => trim($data['17']),
                        'child_mother_email_id' => trim($data['18']),
                        'child_blood_group' => trim($data['19']),
                        'child_address' => trim($data['20']),
                        'child_area' => trim($data['21']),
                        'child_city' => trim($data['22']),
                        'child_pickup_lati' => trim($data['23']),
                        'child_pickup_longi' => trim($data['24']),
                        'child_drop_off_lati' => trim($data['25']),
                        'child_drop_off_longi' => trim($data['26']),
                        'child_nfc_id' => trim($data['27']),
                        'child_sms' => trim($data['28']),
                        'child_push_notification' => trim($data['29']),
                        'child_trip_no_pickup' => $trip_id_pickup,
                        'child_trip_no_drop_off' => $trip_id_drop_off,
                        'child_personal_transport_pickup' => trim($data['30']),
                        'child_personal_transport_drop_off' => trim($data['31']),
                        'child_pickup_time'=> trim($data['32']),
                        'child_dropoff_time'=> trim($data['33']),
                        'child_handicapped_type'=> trim($data['34']),
                        'child_reg_no'=> trim($data['35']),
                    );

                    $parent_app_user_id_exist = $this->Parent_app_user_model->check_parent_email(trim($data['17']));
                    if ($parent_app_user_id_exist) {
                        $parent_app_user_id = $parent_app_user_id_exist;
                    } else {
                        $user_name = trim($data['17']);
                        $number_of_digits = 4;
                        $pin_number = substr(number_format(time() * mt_rand(), 0, '', ''), 0, $number_of_digits);
                        $params_parent_app = array(
                            'parent_app_user_name' => $user_name,
                            'parent_app_user_password' => $auth_code,
                            'parent_app_user_status' => '1',
                            'pin_number' => $pin_number,
                        );

                        $parent_app_user_id = $this->Parent_app_user_model->add_parent_app_user($params_parent_app);
                    }
                    $child_last_id = $this->Child_model->add_child($params);


                    $parent_child_mapping = array(
                        'parent_id' => $parent_app_user_id,
                        'child_id' => $child_last_id,
                    );

                    $parent_child_mapping_id = $this->Parent_child_mapping_model->add_parent_child_mapping($parent_child_mapping);
                }
                fclose($handle);
                 $this->session->set_flashdata('msg', 'Db cleared and added new child list');
                redirect('child/index', $data);
            }
        }
        $this->load->view('child/add_csv', $data);
    }
    /*
     * Adding a new child
     */

    /*
     * Appending studensts with out clearing child table
     */

    function append_csv() {
        $data['page_title'] = 'Child add';
        $settings = $this->Setting_model->get_all_settings();
        $auth_code='123';
        foreach ($settings as $key => $value) {
            
             $auth_code=$value['set_auth_code'];
          }
        if (isset($_POST['submit'])) {

            if($_FILES['csv']['tmp_name']==''){
                 $this->session->set_flashdata('error', 'Please select CSV file');
                 redirect('child/add_csv', $data);
            }
            
            if (($handle = fopen($_FILES['csv']['tmp_name'], "r")) !== FALSE) {
                fgetcsv($handle);
               
                while (($data1 = fgetcsv($handle, 1000, ",")) !== FALSE) {
                    $num = count($data1);
                    for ($c = 0; $c < $num; $c++) {
                        $data[$c] = $data1[$c];
                    }

                    $bus_id_pickup = $this->Bu_model->get_bus_id_by_desc(trim($data['6']));
                    $bus_id_pickup=($bus_id_pickup)?$bus_id_pickup['bus_id']:'0';
                    $trip_id_pickup = $this->Trip_model->get_trip_id(trim($data['7']));
                    $trip_id_pickup=($trip_id_pickup)?$trip_id_pickup['trip_id']:'0';
                    $bus_id_drop_off = $this->Bu_model->get_bus_id_by_desc(trim($data['8']));
                    $bus_id_drop_off=($bus_id_drop_off)?$bus_id_drop_off['bus_id']:'0';
                    $trip_id_drop_off = $this->Trip_model->get_trip_id(trim($data['9']));
                    $trip_id_drop_off=($trip_id_drop_off)?$trip_id_drop_off['trip_id']:'0';
                    $params = array(
                        'child_name' => trim($data['0']),
                        'child_gender' => trim($data['1']),
                        'child_photo' => trim($data['2']),
                        'child_class' => trim($data['3']),
                        'child_section' => trim($data['4']),
                        'child_teacher' => trim($data['5']),
                        'child_bus_no_pickup' => $bus_id_pickup,
                        'child_bus_no_drop_off' => $bus_id_drop_off,
                        'child_drop_off_order' => trim($data['10']),
                        'child_pickup_order' => trim($data['11']),
                        'child_father_name' => trim($data['12']),
                        'child_mother_name' => trim($data['13']),
                        'child_father_tel' => trim($data['14']),
                        'child_mother_tel' => trim($data['15']),
                        'child_home_tel' => trim($data['16']),
                        'child_father_email_id' => trim($data['17']),
                        'child_mother_email_id' => trim($data['18']),
                        'child_blood_group' => trim($data['19']),
                        'child_address' => trim($data['20']),
                        'child_area' => trim($data['21']),
                        'child_city' => trim($data['22']),
                        'child_pickup_lati' => trim($data['23']),
                        'child_pickup_longi' => trim($data['24']),
                        'child_drop_off_lati' => trim($data['25']),
                        'child_drop_off_longi' => trim($data['26']),
                        'child_nfc_id' => trim($data['27']),
                        'child_sms' => trim($data['28']),
                        'child_push_notification' => trim($data['29']),
                        'child_trip_no_pickup' => $trip_id_pickup,
                        'child_trip_no_drop_off' => $trip_id_drop_off,
                        'child_personal_transport_pickup' => trim($data['30']),
                        'child_personal_transport_drop_off' => trim($data['31']),
                        'child_pickup_time'=> trim($data['32']),
                        'child_dropoff_time'=> trim($data['33']),
                        'child_handicapped_type'=> trim($data['34']),
                        'child_reg_no'=> trim($data['35']),
                    );

                    $parent_app_user_id_exist = $this->Parent_app_user_model->check_parent_email(trim($data['17']));
                    if ($parent_app_user_id_exist) {
                        $parent_app_user_id = $parent_app_user_id_exist;
                    } else {
                        $user_name = trim($data['17']);
                        $number_of_digits = 4;
                        $pin_number = substr(number_format(time() * mt_rand(), 0, '', ''), 0, $number_of_digits);
                        $params_parent_app = array(
                            'parent_app_user_name' => $user_name,
                            'parent_app_user_password' => $auth_code,
                            'parent_app_user_status' => '1',
                            'pin_number' => $pin_number,
                        );

                        $parent_app_user_id = $this->Parent_app_user_model->add_parent_app_user($params_parent_app);
                    }
                    $child_last_id = $this->Child_model->add_child($params);


                    $parent_child_mapping = array(
                        'parent_id' => $parent_app_user_id,
                        'child_id' => $child_last_id,
                    );

                    $parent_child_mapping_id = $this->Parent_child_mapping_model->add_parent_child_mapping($parent_child_mapping);
                }
                fclose($handle);
                   $this->session->set_flashdata('msg', 'New list is appended to existing db');
                redirect('child/index', $data);
            }
        }
        $this->load->view('child/append_csv', $data);
    }
    /*
     * Adding a new child
     */

    function edit_csv() {
        $data['page_title'] = 'Child edit list';
        $settings = $this->Setting_model->get_all_settings();
        $auth_code='123';
        foreach ($settings as $key => $value) {
            
             $auth_code=$value['set_auth_code'];
          }
        if (isset($_POST['submit'])) {

            if($_FILES['csv']['tmp_name']==''){
                 $this->session->set_flashdata('error', 'Please select CSV file');
                 redirect('child/add_csv', $data);
            }
            
            if (($handle = fopen($_FILES['csv']['tmp_name'], "r")) !== FALSE) {
                fgetcsv($handle);
//                $settings = $this->Setting_model->get_all_settings();
//                 $is_truncate='No';
//                 foreach ($settings as $key => $value) {
//                       $is_truncate = $value['truncate'];
//                        }
//                if($is_truncate=='Yes'){     
//                $truncate = $this->Child_model->truncate_child();
//                $truncate1 = $this->Parent_app_user_model->truncate_Parent_app_user();
//                $truncate2 = $this->Parent_child_mapping_model->truncate_Parent_child_mapping();                    
//                }
                while (($data1 = fgetcsv($handle, 1000, ",")) !== FALSE) {
                    $num = count($data1);
                    for ($c = 0; $c < $num; $c++) {
                        $data[$c] = $data1[$c];
                    }

                    $bus_id_pickup = $this->Bu_model->get_bus_id_by_desc(trim($data['6']));
                    $bus_id_pickup=($bus_id_pickup)?$bus_id_pickup['bus_id']:'0';
                    $trip_id_pickup = $this->Trip_model->get_trip_id(trim($data['7']));
                    $trip_id_pickup=($trip_id_pickup)?$trip_id_pickup['trip_id']:'0';
                    $bus_id_drop_off = $this->Bu_model->get_bus_id_by_desc(trim($data['8']));
                    $bus_id_drop_off=($bus_id_drop_off)?$bus_id_drop_off['bus_id']:'0';
                    $trip_id_drop_off = $this->Trip_model->get_trip_id(trim($data['9']));
                    $trip_id_drop_off=($trip_id_drop_off)?$trip_id_drop_off['trip_id']:'0';
                    $params = array(
                        'child_name' => trim($data['0']),
                        'child_gender' => trim($data['1']),
                        'child_class' => trim($data['3']),
                        'child_section' => trim($data['4']),
                        'child_bus_no_pickup' => $bus_id_pickup,
                        'child_bus_no_drop_off' => $bus_id_drop_off,
                        'child_drop_off_order' => trim($data['10']),
                        'child_pickup_order' => trim($data['11']),
                        'child_father_name' => trim($data['12']),
                        'child_mother_name' => trim($data['13']),                      
                        'child_nfc_id' => trim($data['27']),                      
                        'child_push_notification' => trim($data['29']),
                        'child_trip_no_pickup' => $trip_id_pickup,
                        'child_trip_no_drop_off' => $trip_id_drop_off,
                    );
                   $child_reg_no=trim($data['35']); 
                    $child_last_id = $this->Child_model->update_child_reg_no($child_reg_no,$params);

                }
                fclose($handle);
                 $this->session->set_flashdata('msg', 'Existing child list is updated with new values');
                redirect('child/index', $data);
            }
        }
        $this->load->view('child/edit_csv', $data);
    }

    function search($offset = 0) {
        $data['page_title'] = 'Child';
        $data['bus'] = $this->Bu_model->get_all_bus();
        $data['registration_number'] = $this->Child_model->get_all_child_reg_num();

        if (isset($_GET)) {
           $pickup = $this->input->get('pickup'); 
            $dropoff = $this->input->get('dropoff');
            $registration = $this->input->get('registration');
            $child_name = $this->input->get('child_name');
            $email = $this->input->get('email');
            $phone = $this->input->get('phone');
             if ($pickup=='' && $dropoff=='' && $registration=='' && $child_name=='' && $email == '' && $phone == '') {
              // $error = '';
               $this->session->set_flashdata('error', 'Please select one option');
             // $this->load->view('child/index', $data);                 
               redirect('child/index');
                 } else {
                if ($pickup) {
                    //pagination----------------------

                    $config = array();
                    $config['suffix'] = '?pickup='.$pickup.'&dropoff='.$dropoff.'&registration='.$registration.'&child_name='.$child_name.'&email='.$email.'&phone='.$phone;  
                    $config["base_url"] = base_url() . "child/search/";
                    $total_count_all = $this->Child_model->count_pickup($pickup);
                    $config["total_rows"] = $total_count_all['total'];
                    $config["per_page"] = 100;
                    $config["uri_segment"] = 3;
//                    $config['enable_query_strings'] = TRUE;
//                    $config['reuse_query_string'] = TRUE;
//                    $config['query_string_segment'] =  '?pickup='.$pickup.'&dropoff='.$dropoff.'&registration='.$registration;  
                    $config['full_tag_open'] = "<ul class='pagination'>";
                    $config['full_tag_close'] = '</ul>';
                    $config['num_tag_open'] = '<li>';
                    $config['num_tag_close'] = '</li>';
                    $config['cur_tag_open'] = '<li class="active"><a href="#">';
                    $config['cur_tag_close'] = '</a></li>';
                    $config['prev_tag_open'] = '<li>';
                    $config['prev_tag_close'] = '</li>';
                    $config['first_tag_open'] = '<li>';
                    $config['first_tag_close'] = '</li>';
                    $config['last_tag_open'] = '<li>';
                    $config['last_tag_close'] = '</li>';
                    $config['prev_link'] = '<i class="fa fa-long-arrow-left"></i>Previous Page';
                    $config['prev_tag_open'] = '<li>';
                    $config['prev_tag_close'] = '</li>';
                    $config['next_link'] = 'Next Page<i class="fa fa-long-arrow-right"></i>';
                    $config['next_tag_open'] = '<li>';
                    $config['next_tag_close'] = '</li>';
    //

//    print_r($config);

                    $this->pagination->initialize($config);

                    $page = ($this->uri->segment(3)) ? $this->uri->segment(3) : 0;

                    $data1 = $this->Child_model->get_all_child_index_pickup($pickup, $config["per_page"], $page);
                    // echo $this->db->last_query();
                    //  echo count($data1);
                    for ($j = 0; $j < count($data1); $j++) {
                        $child_bus_no_pickup = $data1[$j]['child_bus_no_pickup'];
                        $bus_number = $this->Bu_model->get_bu($child_bus_no_pickup);
                        $data1[$j]['child_bus_no_pickup'] = $bus_number['bus_desc'];

                        $child_bus_no_drop_off = $data1[$j]['child_bus_no_drop_off'];
                        $bus_number_off = $this->Bu_model->get_bu($child_bus_no_drop_off);
                        $data1[$j]['child_bus_no_drop_off'] = $bus_number_off['bus_desc'];
                        //trip
                        $child_trip_no_drop_off = $data1[$j]['child_trip_no_drop_off'];
                        $trip_number_off = $this->Trip_model->get_trip($child_trip_no_drop_off);
                        $data1[$j]['child_trip_no_drop_off'] = $trip_number_off['trip_no'];

                        $child_trip_no_pickup = $data1[$j]['child_trip_no_pickup'];
                        $trip_number = $this->Trip_model->get_trip($child_trip_no_pickup);
                        $data1[$j]['child_trip_no_pickup'] = $trip_number['trip_no'];
                        
                        $child_id = $data1[$j]['child_id'];
             $signed_status = $this->Parent_app_user_model->get_signedup_or_not($child_id);
             $data1[$j]['signed_status'] = $signed_status;
                        
                    }
                    $data['child'] = $data1;
                    $data['list_num'] = $page;
//          print_r($data);
                    $data['links'] = $this->pagination->create_links();
                    //     print_r($data);
                    //   echo $this->db->last_query();
                }
                 if ($dropoff) {
                    //pagination----------------------

                    $config = array();
                     $config['suffix'] = '?pickup='.$pickup.'&dropoff='.$dropoff.'&registration='.$registration.'&child_name='.$child_name.'&email='.$email.'&phone='.$phone;  
                    $config["base_url"] = base_url() . "child/search/";
                    $total_count_all = $this->Child_model->count_pickup($dropoff);
                    $config["total_rows"] = $total_count_all['total'];
                    $config["per_page"] = 100;
                    $config["uri_segment"] = 3;

                    $config['full_tag_open'] = "<ul class='pagination'>";
                    $config['full_tag_close'] = '</ul>';
                    $config['num_tag_open'] = '<li>';
                    $config['num_tag_close'] = '</li>';
                    $config['cur_tag_open'] = '<li class="active"><a href="#">';
                    $config['cur_tag_close'] = '</a></li>';
                    $config['prev_tag_open'] = '<li>';
                    $config['prev_tag_close'] = '</li>';
                    $config['first_tag_open'] = '<li>';
                    $config['first_tag_close'] = '</li>';
                    $config['last_tag_open'] = '<li>';
                    $config['last_tag_close'] = '</li>';



                    $config['prev_link'] = '<i class="fa fa-long-arrow-left"></i>Previous Page';
                    $config['prev_tag_open'] = '<li>';
                    $config['prev_tag_close'] = '</li>';


                    $config['next_link'] = 'Next Page<i class="fa fa-long-arrow-right"></i>';
                    $config['next_tag_open'] = '<li>';
                    $config['next_tag_close'] = '</li>';


                    $this->pagination->initialize($config);

                    $page = ($this->uri->segment(3)) ? $this->uri->segment(3) : 0;

                    $data1 = $this->Child_model->get_all_child_index_pickup($dropoff, $config["per_page"], $page);
                    // echo $this->db->last_query();
                    //  echo count($data1);
                    for ($j = 0; $j < count($data1); $j++) {
                        $child_bus_no_pickup = $data1[$j]['child_bus_no_pickup'];
                        $bus_number = $this->Bu_model->get_bu($child_bus_no_pickup);
                        $data1[$j]['child_bus_no_pickup'] = $bus_number['bus_desc'];

                        $child_bus_no_drop_off = $data1[$j]['child_bus_no_drop_off'];
                        $bus_number_off = $this->Bu_model->get_bu($child_bus_no_drop_off);
                        $data1[$j]['child_bus_no_drop_off'] = $bus_number_off['bus_desc'];
                        //trip
                        $child_trip_no_drop_off = $data1[$j]['child_trip_no_drop_off'];
                        $trip_number_off = $this->Trip_model->get_trip($child_trip_no_drop_off);
                        $data1[$j]['child_trip_no_drop_off'] = $trip_number_off['trip_no'];

                        $child_trip_no_pickup = $data1[$j]['child_trip_no_pickup'];
                        $trip_number = $this->Trip_model->get_trip($child_trip_no_pickup);
                        $data1[$j]['child_trip_no_pickup'] = $trip_number['trip_no'];
                        
                        $child_id = $data1[$j]['child_id'];
             $signed_status = $this->Parent_app_user_model->get_signedup_or_not($child_id);
             $data1[$j]['signed_status'] = $signed_status;
             
                    }
                    $data['child'] = $data1;
                    $data['list_num'] = $page;;
                    $data['links'] = $this->pagination->create_links();
                }
                
                 if ($registration) {
                    //pagination----------------------

                    $config = array();
                     $config['suffix'] = '?pickup='.$pickup.'&dropoff='.$dropoff.'&registration='.$registration.'&child_name='.$child_name.'&email='.$email.'&phone='.$phone;    
                    $config["base_url"] = base_url() . "child/search/";
                    $total_count_all = $this->Child_model->count_registration($registration);
                   // echo $this->db->last_query();                    exit();
                    $config["total_rows"] = $total_count_all['total'];
                    $config["per_page"] = 100;
                    $config["uri_segment"] = 3;

                    $config['full_tag_open'] = "<ul class='pagination'>";
                    $config['full_tag_close'] = '</ul>';
                    $config['num_tag_open'] = '<li>';
                    $config['num_tag_close'] = '</li>';
                    $config['cur_tag_open'] = '<li class="active"><a href="#">';
                    $config['cur_tag_close'] = '</a></li>';
                    $config['prev_tag_open'] = '<li>';
                    $config['prev_tag_close'] = '</li>';
                    $config['first_tag_open'] = '<li>';
                    $config['first_tag_close'] = '</li>';
                    $config['last_tag_open'] = '<li>';
                    $config['last_tag_close'] = '</li>';



                    $config['prev_link'] = '<i class="fa fa-long-arrow-left"></i>Previous Page';
                    $config['prev_tag_open'] = '<li>';
                    $config['prev_tag_close'] = '</li>';


                    $config['next_link'] = 'Next Page<i class="fa fa-long-arrow-right"></i>';
                    $config['next_tag_open'] = '<li>';
                    $config['next_tag_close'] = '</li>';


                    $this->pagination->initialize($config);

                    $page = ($this->uri->segment(3)) ? $this->uri->segment(3) : 0;

                    $data1 = $this->Child_model->get_all_child_index_registration($registration, $config["per_page"], $page);
                    // echo $this->db->last_query();
                    //  echo count($data1);
                    for ($j = 0; $j < count($data1); $j++) {
                        $child_bus_no_pickup = $data1[$j]['child_bus_no_pickup'];
                        $bus_number = $this->Bu_model->get_bu($child_bus_no_pickup);
                        $data1[$j]['child_bus_no_pickup'] = $bus_number['bus_desc'];

                        $child_bus_no_drop_off = $data1[$j]['child_bus_no_drop_off'];
                        $bus_number_off = $this->Bu_model->get_bu($child_bus_no_drop_off);
                        $data1[$j]['child_bus_no_drop_off'] = $bus_number_off['bus_desc'];
                        //trip
                        $child_trip_no_drop_off = $data1[$j]['child_trip_no_drop_off'];
                        $trip_number_off = $this->Trip_model->get_trip($child_trip_no_drop_off);
                        $data1[$j]['child_trip_no_drop_off'] = $trip_number_off['trip_no'];

                        $child_trip_no_pickup = $data1[$j]['child_trip_no_pickup'];
                        $trip_number = $this->Trip_model->get_trip($child_trip_no_pickup);
                        $data1[$j]['child_trip_no_pickup'] = $trip_number['trip_no'];
                        
                        $child_id = $data1[$j]['child_id'];
             $signed_status = $this->Parent_app_user_model->get_signedup_or_not($child_id);
             $data1[$j]['signed_status'] = $signed_status;
                    }
                    $data['child'] = $data1;
                    $data['list_num'] = $page;;
                    $data['links'] = $this->pagination->create_links();
                }
                
                 if ($child_name) {
                    //pagination----------------------

                    $config = array();
                     $config['suffix'] = '?pickup='.$pickup.'&dropoff='.$dropoff.'&registration='.$registration.'&child_name='.$child_name.'&email='.$email.'&phone='.$phone;   
                    $config["base_url"] = base_url() . "child/search/";
                    $total_count_all = $this->Child_model->count_child_name($child_name);
                   // echo $this->db->last_query();                    exit();
                    $config["total_rows"] = $total_count_all['total'];
                    $config["per_page"] = 100;
                    $config["uri_segment"] = 3;

                    $config['full_tag_open'] = "<ul class='pagination'>";
                    $config['full_tag_close'] = '</ul>';
                    $config['num_tag_open'] = '<li>';
                    $config['num_tag_close'] = '</li>';
                    $config['cur_tag_open'] = '<li class="active"><a href="#">';
                    $config['cur_tag_close'] = '</a></li>';
                    $config['prev_tag_open'] = '<li>';
                    $config['prev_tag_close'] = '</li>';
                    $config['first_tag_open'] = '<li>';
                    $config['first_tag_close'] = '</li>';
                    $config['last_tag_open'] = '<li>';
                    $config['last_tag_close'] = '</li>';



                    $config['prev_link'] = '<i class="fa fa-long-arrow-left"></i>Previous Page';
                    $config['prev_tag_open'] = '<li>';
                    $config['prev_tag_close'] = '</li>';


                    $config['next_link'] = 'Next Page<i class="fa fa-long-arrow-right"></i>';
                    $config['next_tag_open'] = '<li>';
                    $config['next_tag_close'] = '</li>';


                    $this->pagination->initialize($config);

                    $page = ($this->uri->segment(3)) ? $this->uri->segment(3) : 0;

                    $data1 = $this->Child_model->get_all_child_index_child_name($child_name, $config["per_page"], $page);
                    //echo $this->db->last_query(); exit();
                    //  echo count($data1);
                    for ($j = 0; $j < count($data1); $j++) {
                        $child_bus_no_pickup = $data1[$j]['child_bus_no_pickup'];
                        $bus_number = $this->Bu_model->get_bu($child_bus_no_pickup);
                        $data1[$j]['child_bus_no_pickup'] = $bus_number['bus_desc'];

                        $child_bus_no_drop_off = $data1[$j]['child_bus_no_drop_off'];
                        $bus_number_off = $this->Bu_model->get_bu($child_bus_no_drop_off);
                        $data1[$j]['child_bus_no_drop_off'] = $bus_number_off['bus_desc'];
                        //trip
                        $child_trip_no_drop_off = $data1[$j]['child_trip_no_drop_off'];
                        $trip_number_off = $this->Trip_model->get_trip($child_trip_no_drop_off);
                        $data1[$j]['child_trip_no_drop_off'] = $trip_number_off['trip_no'];

                        $child_trip_no_pickup = $data1[$j]['child_trip_no_pickup'];
                        $trip_number = $this->Trip_model->get_trip($child_trip_no_pickup);
                        $data1[$j]['child_trip_no_pickup'] = $trip_number['trip_no'];
                        
                        $child_id = $data1[$j]['child_id'];
             $signed_status = $this->Parent_app_user_model->get_signedup_or_not($child_id);
             $data1[$j]['signed_status'] = $signed_status;
                    }
                    $data['child'] = $data1;
                    $data['list_num'] = $page;;
                    $data['links'] = $this->pagination->create_links();
                }
                
                
                
                
                 if ($email) {
                    //pagination----------------------

                    $config = array();
                     $config['suffix'] = '?pickup='.$pickup.'&dropoff='.$dropoff.'&registration='.$registration.'&child_name='.$child_name.'&email='.$email.'&phone='.$phone;   
                    $config["base_url"] = base_url() . "child/search/";
                    $total_count_all = $this->Child_model->count_child_email($email);
                   // echo $this->db->last_query();                    exit();
                    $config["total_rows"] = $total_count_all['total'];
                    $config["per_page"] = 100;
                    $config["uri_segment"] = 3;

                    $config['full_tag_open'] = "<ul class='pagination'>";
                    $config['full_tag_close'] = '</ul>';
                    $config['num_tag_open'] = '<li>';
                    $config['num_tag_close'] = '</li>';
                    $config['cur_tag_open'] = '<li class="active"><a href="#">';
                    $config['cur_tag_close'] = '</a></li>';
                    $config['prev_tag_open'] = '<li>';
                    $config['prev_tag_close'] = '</li>';
                    $config['first_tag_open'] = '<li>';
                    $config['first_tag_close'] = '</li>';
                    $config['last_tag_open'] = '<li>';
                    $config['last_tag_close'] = '</li>';



                    $config['prev_link'] = '<i class="fa fa-long-arrow-left"></i>Previous Page';
                    $config['prev_tag_open'] = '<li>';
                    $config['prev_tag_close'] = '</li>';


                    $config['next_link'] = 'Next Page<i class="fa fa-long-arrow-right"></i>';
                    $config['next_tag_open'] = '<li>';
                    $config['next_tag_close'] = '</li>';


                    $this->pagination->initialize($config);

                    $page = ($this->uri->segment(3)) ? $this->uri->segment(3) : 0;

                    $data1 = $this->Child_model->get_all_child_index_child_email($email, $config["per_page"], $page);
                    //echo $this->db->last_query(); exit();
                    //  echo count($data1);
                    for ($j = 0; $j < count($data1); $j++) {
                        $child_bus_no_pickup = $data1[$j]['child_bus_no_pickup'];
                        $bus_number = $this->Bu_model->get_bu($child_bus_no_pickup);
                        $data1[$j]['child_bus_no_pickup'] = $bus_number['bus_desc'];

                        $child_bus_no_drop_off = $data1[$j]['child_bus_no_drop_off'];
                        $bus_number_off = $this->Bu_model->get_bu($child_bus_no_drop_off);
                        $data1[$j]['child_bus_no_drop_off'] = $bus_number_off['bus_desc'];
                        //trip
                        $child_trip_no_drop_off = $data1[$j]['child_trip_no_drop_off'];
                        $trip_number_off = $this->Trip_model->get_trip($child_trip_no_drop_off);
                        $data1[$j]['child_trip_no_drop_off'] = $trip_number_off['trip_no'];

                        $child_trip_no_pickup = $data1[$j]['child_trip_no_pickup'];
                        $trip_number = $this->Trip_model->get_trip($child_trip_no_pickup);
                        $data1[$j]['child_trip_no_pickup'] = $trip_number['trip_no'];
                        
                        $child_id = $data1[$j]['child_id'];
             $signed_status = $this->Parent_app_user_model->get_signedup_or_not($child_id);
             $data1[$j]['signed_status'] = $signed_status;
                    }
                    $data['child'] = $data1;
                    $data['list_num'] = $page;;
                    $data['links'] = $this->pagination->create_links();
                }
                
                  if ($phone) {
                    //pagination----------------------

                    $config = array();
                     $config['suffix'] = '?pickup='.$pickup.'&dropoff='.$dropoff.'&registration='.$registration.'&child_name='.$child_name.'&email='.$email.'&phone='.$phone;  
                    $config["base_url"] = base_url() . "child/search/";
                    $total_count_all = $this->Child_model->count_child_phone($phone);
                   // echo $this->db->last_query();                    exit();
                    $config["total_rows"] = $total_count_all['total'];
                    $config["per_page"] = 100;
                    $config["uri_segment"] = 3;

                    $config['full_tag_open'] = "<ul class='pagination'>";
                    $config['full_tag_close'] = '</ul>';
                    $config['num_tag_open'] = '<li>';
                    $config['num_tag_close'] = '</li>';
                    $config['cur_tag_open'] = '<li class="active"><a href="#">';
                    $config['cur_tag_close'] = '</a></li>';
                    $config['prev_tag_open'] = '<li>';
                    $config['prev_tag_close'] = '</li>';
                    $config['first_tag_open'] = '<li>';
                    $config['first_tag_close'] = '</li>';
                    $config['last_tag_open'] = '<li>';
                    $config['last_tag_close'] = '</li>';



                    $config['prev_link'] = '<i class="fa fa-long-arrow-left"></i>Previous Page';
                    $config['prev_tag_open'] = '<li>';
                    $config['prev_tag_close'] = '</li>';


                    $config['next_link'] = 'Next Page<i class="fa fa-long-arrow-right"></i>';
                    $config['next_tag_open'] = '<li>';
                    $config['next_tag_close'] = '</li>';


                    $this->pagination->initialize($config);

                    $page = ($this->uri->segment(3)) ? $this->uri->segment(3) : 0;

                    $data1 = $this->Child_model->get_all_child_index_child_phone($phone, $config["per_page"], $page);
                    //echo $this->db->last_query(); exit();
                    //  echo count($data1);
                    for ($j = 0; $j < count($data1); $j++) {
                        $child_bus_no_pickup = $data1[$j]['child_bus_no_pickup'];
                        $bus_number = $this->Bu_model->get_bu($child_bus_no_pickup);
                        $data1[$j]['child_bus_no_pickup'] = $bus_number['bus_desc'];

                        $child_bus_no_drop_off = $data1[$j]['child_bus_no_drop_off'];
                        $bus_number_off = $this->Bu_model->get_bu($child_bus_no_drop_off);
                        $data1[$j]['child_bus_no_drop_off'] = $bus_number_off['bus_desc'];
                        //trip
                        $child_trip_no_drop_off = $data1[$j]['child_trip_no_drop_off'];
                        $trip_number_off = $this->Trip_model->get_trip($child_trip_no_drop_off);
                        $data1[$j]['child_trip_no_drop_off'] = $trip_number_off['trip_no'];

                        $child_trip_no_pickup = $data1[$j]['child_trip_no_pickup'];
                        $trip_number = $this->Trip_model->get_trip($child_trip_no_pickup);
                        $data1[$j]['child_trip_no_pickup'] = $trip_number['trip_no'];
                        
                        $child_id = $data1[$j]['child_id'];
             $signed_status = $this->Parent_app_user_model->get_signedup_or_not($child_id);
             $data1[$j]['signed_status'] = $signed_status;
                    }
                    $data['child'] = $data1;
                    $data['list_num'] = $page;;
                    $data['links'] = $this->pagination->create_links();
                }
            }


            $this->load->view('child/index', $data);
        }
    }

    
    
    
    
    
    
    public function download() {
        $image_names = $this->Child_model->get_all_child();
        foreach($image_names as $names){
           // echo $names['child_photo'];
           if(!file_exists(FCPATH . "uploads/std/".$names['child_photo']))
           {
            $data1[] =$names;
           }
          }
        $data['register_number']  =$data1;
        $html=  $this->load->view('child/pdf',$data,true);
        $this->load->helper('dompdf');   
        pdf_create($html);
       
    }
    
    
   
    function download_child_details_with_bus() {
        $data1 = $this->Child_model->get_all_child_with_bus_details();
        //  echo $this->db->last_query();

        for ($j = 0; $j < count($data1); $j++) {
            $child_bus_no_pickup = $data1[$j]['child_bus_no_pickup'];
            $bus_number = $this->Bu_model->get_bu($child_bus_no_pickup);
            $data1[$j]['child_bus_no_pickup'] = $bus_number['bus_desc'];

            $child_bus_no_drop_off = $data1[$j]['child_bus_no_drop_off'];
            $bus_number_off = $this->Bu_model->get_bu($child_bus_no_drop_off);
            $data1[$j]['child_bus_no_drop_off'] = $bus_number_off['bus_desc'];
            //trip
            $child_trip_no_drop_off = $data1[$j]['child_trip_no_drop_off'];
            $trip_number_off = $this->Trip_model->get_trip($child_trip_no_drop_off);
            $data1[$j]['child_trip_no_drop_off'] = $trip_number_off['trip_no'];

            $child_trip_no_pickup = $data1[$j]['child_trip_no_pickup'];
            $trip_number = $this->Trip_model->get_trip($child_trip_no_pickup);
            $data1[$j]['child_trip_no_pickup'] = $trip_number['trip_no'];
        }
//        $data['child'] = $data1;
       //print_r($data1[0]);
//            $this->load->helper('csv');
            
            $result = $data1;
            header("Content-type: application/csv");
            header("Content-Disposition: attachment; filename=\"BusList".".csv\"");
            header("Pragma: no-cache");
            header("Expires: 0");
            $handle = fopen('php://output', 'w'); 
            fputcsv($handle, array('#','Name', 'REG #', 'CLASS', 'SECTION', 'PICKUP BUS', 'Trip # (Pickup)', 'DROPOFF BUS', 'Trip # (Drop Off)', 'Father Name', 'MOB NO 1','Primary Email','PUSH NOTIFICATION'));
                          $i = 1;
                          foreach ($result as $data) { 
                              fputcsv($handle, array($i, $data["child_name"], $data["child_nfc_id"], $data["child_class"], $data["child_section"], $data["child_bus_no_pickup"], $data["child_trip_no_pickup"],$data["child_bus_no_drop_off"], $data["child_trip_no_drop_off"], $data["child_father_name"], $data["child_father_tel"], $data["child_father_email_id"],$data["child_push_notification"]));
                              $i++;
                          }
                              fclose($handle);
                          exit;
    } 
    
    
     function download_child_details_with_bus_downloading_and_updating_with_newvalues() {
        $data1 = $this->Child_model->get_all_child_with_bus_details();
        //  echo $this->db->last_query();

        for ($j = 0; $j < count($data1); $j++) {
            $child_bus_no_pickup = $data1[$j]['child_bus_no_pickup'];
            $bus_number = $this->Bu_model->get_bu($child_bus_no_pickup);
            $data1[$j]['child_bus_no_pickup'] = $bus_number['bus_desc'];

            $child_bus_no_drop_off = $data1[$j]['child_bus_no_drop_off'];
            $bus_number_off = $this->Bu_model->get_bu($child_bus_no_drop_off);
            $data1[$j]['child_bus_no_drop_off'] = $bus_number_off['bus_desc'];
            //trip
            $child_trip_no_drop_off = $data1[$j]['child_trip_no_drop_off'];
            $trip_number_off = $this->Trip_model->get_trip($child_trip_no_drop_off);
            $data1[$j]['child_trip_no_drop_off'] = $trip_number_off['trip_no'];

            $child_trip_no_pickup = $data1[$j]['child_trip_no_pickup'];
            $trip_number = $this->Trip_model->get_trip($child_trip_no_pickup);
            $data1[$j]['child_trip_no_pickup'] = $trip_number['trip_no'];
        }
//        $data['child'] = $data1;
//            $this->load->helper('csv');
            
            $result = $data1;
            header("Content-type: application/csv");
            header("Content-Disposition: attachment; filename=\"StudentList".".csv\"");
            header("Pragma: no-cache");
            header("Expires: 0");
            $handle = fopen('php://output', 'w'); 
            fputcsv($handle, array('Name(*)', 'GENDER(*)', 'PHOTO', 'CLASS(*)', 'SECTION(*)', 'Teacher', 'Pickup Bus(*)', 'Trip # (Pickup)(*)', 'DROPOFF BUS(*)', 'Trip # (Drop Off)(*)',
                'Drop off Order #(*)','Pickup Order #(*)','Fathers Name(*)','Mothers Name(*)','MOB NO 1','MOB NO 2','Tel(HOME)','Primary Email','Secondary Email','Blood Group',
                'Address','Area','City','PICK-UP Latitude','PICK-UP Longitude','DROP OFF Latitude','DROP OFF Longitude','NFC ID(*)','SMS','Push Notification(*)','Own Transport(PICKUP)','Own Transport(DROPOFF)',
                'Pickup time( eg: 9.30)* times are in 24 hr format without sec','Drop off time ( eg: 9.30)* times are in 24 hr formatwithout sec','Notes (1.Do not drop-off child without gaurdian prescence 2.Child is handicapped 3.none)',
                'Student ID(*)'));
                          $i = 1;
                          foreach ($result as $data) { 
                              fputcsv($handle, array($data["child_name"], $data["child_gender"], $data["child_photo"], $data["child_class"], $data["child_section"], $data["child_teacher"],$data["child_bus_no_pickup"], 
                                  $data["child_trip_no_pickup"], $data["child_bus_no_drop_off"], $data["child_trip_no_drop_off"], $data["child_drop_off_order"], $data["child_pickup_order"], $data["child_father_name"]
                                      , $data["child_mother_name"], $data["child_father_tel"], $data["child_mother_tel"], $data["child_home_tel"], $data["child_father_email_id"], $data["child_mother_email_id"]
                                      , $data["child_blood_group"], $data["child_address"], $data["child_area"], $data["child_city"], $data["child_pickup_lati"], $data["child_pickup_longi"]
                                      , $data["child_drop_off_lati"], $data["child_drop_off_longi"], $data["child_nfc_id"], $data["child_sms"], $data["child_push_notification"], $data["child_personal_transport_pickup"]
                                      , $data["child_personal_transport_drop_off"], $data["child_pickup_time"], $data["child_dropoff_time"], $data["child_handicapped_type"], $data["child_reg_no"]));
                              $i++;
                          }
                              fclose($handle);
                          exit;
    } 
    
}
