<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Device_app_user extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Device_app_user_model');
        $this->load->model('Attendance_device_model');
          $this->load->library('pagination');
             $this->load->model('User_model');
           if (!$this->User_model->auth_session()) {
            redirect('Login');
        }
    } 

    /*
     * Listing of device_app_user
     */
    function index()
    {
         $data['page_title'] = 'Device User';
        $config = array();
        $config["base_url"] = base_url() . "device_app_user/index";
        $config["total_rows"] = $this->Device_app_user_model->get_all_device_app_user_count();
        $config["per_page"] = 30;
        $config["uri_segment"] = 3;
        $config['full_tag_open'] = "<ul class='pagination'>";
        $config['full_tag_close'] = '</ul>';
        $config['num_tag_open'] = '<li>';
        $config['num_tag_close'] = '</li>';
        $config['cur_tag_open'] = '<li class="active"><a href="#">';
        $config['cur_tag_close'] = '</a></li>';
        $config['prev_tag_open'] = '<li>';
        $config['prev_tag_close'] = '</li>';
        $config['first_tag_open'] = '<li>';
        $config['first_tag_close'] = '</li>';
        $config['last_tag_open'] = '<li>';
        $config['last_tag_close'] = '</li>';



        $config['prev_link'] = '<i class="fa fa-long-arrow-left"></i>Previous Page';
        $config['prev_tag_open'] = '<li>';
        $config['prev_tag_close'] = '</li>';


        $config['next_link'] = 'Next Page<i class="fa fa-long-arrow-right"></i>';
        $config['next_tag_open'] = '<li>';
        $config['next_tag_close'] = '</li>';


         $this->pagination->initialize($config);
         $page = ($this->uri->segment(3)) ? $this->uri->segment(3) : 0;

          $data1 = $this->Device_app_user_model->get_all_device_app_user($config["per_page"], $page);
        
         for ($j = 0; $j < count($data1); $j++) {
            $device_app_user_device_id = $data1[$j]['device_app_user_device_id'];
            $device_name = $this->Attendance_device_model->get_attendance_device($device_app_user_device_id);
            $data1[$j]['device_app_user_device_id'] = $device_name['device_name'];
           
        }
        
        $data['device_app_user']=$data1;
    
        $this->load->view('device_app_user/index',$data);
    }

    /*
     * Adding a new device_app_user
     */
    function add()
    {   
          $data['page_title'] = 'Device User';
           $data['devices'] = $this->Attendance_device_model->get_attendance_device_all();
          $this->load->library('form_validation');

		$this->form_validation->set_rules('device_app_user_password','Device App User Password','required');
		$this->form_validation->set_rules('device_app_user_name','Device App User Name','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'device_app_user_password' => $this->input->post('device_app_user_password'),
				'device_app_user_name' => $this->input->post('device_app_user_name'),
				'device_app_user_device_id' => $this->input->post('device_app_user_device_id'),
				'device_user_type' => $this->input->post('device_user_type'),
            );
            
            $device_app_user_id = $this->Device_app_user_model->add_device_app_user($params);
            redirect('device_app_user/index');
        }
        else
        {            
            $this->load->view('device_app_user/add',$data);
        }
    }  

    /*
     * Editing a device_app_user
     */
    function edit($device_app_user_id)
    {   
          $data['page_title'] = 'Device User';
          $data['devices'] = $this->Attendance_device_model->get_attendance_device_all();
        // check if the device_app_user exists before trying to edit it
        $data['device_app_user'] = $this->Device_app_user_model->get_device_app_user($device_app_user_id);
        
        if(isset($data['device_app_user']['device_app_user_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('device_app_user_password','Device App User Password','required');
			$this->form_validation->set_rules('device_app_user_name','Device App User Name','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'device_app_user_password' => $this->input->post('device_app_user_password'),
					'device_app_user_name' => $this->input->post('device_app_user_name'),
					'device_app_user_device_id' => $this->input->post('device_app_user_device_id'),
					'device_user_type' => $this->input->post('device_user_type'),
                );

                $this->Device_app_user_model->update_device_app_user($device_app_user_id,$params);            
                redirect('device_app_user/index');
            }
            else
            {
                $this->load->view('device_app_user/edit',$data);
            }
        }
        else
            show_error('The device_app_user you are trying to edit does not exist.');
    } 

    /*
     * Deleting device_app_user
     */
    function remove($device_app_user_id)
    {
        $device_app_user = $this->Device_app_user_model->get_device_app_user($device_app_user_id);

        // check if the device_app_user exists before trying to delete it
        if(isset($device_app_user['device_app_user_id']))
        {
            $this->Device_app_user_model->delete_device_app_user($device_app_user_id);
            redirect('device_app_user/index');
        }
        else
            show_error('The device_app_user you are trying to delete does not exist.');
    }
     function change_status()
    {
      $user_id =  $this->uri->segment(3);
      $status =  $this->uri->segment(4);
         if($status==0)
         {
             $status=1;
         }
         else
         {
             $status=0;
         }
      // echo $status;
        // check if the child exists before trying to update it
        if($user_id)
        {
           $this->Device_app_user_model->status_device_app_user($user_id,$status);
         //   echo $this->db->last_query(); exit();
            redirect('device_app_user/index');
        }
        else
            show_error('The child you are trying to delete does not exist.');
    }
}
