<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Logo_image extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Logo_image_model');
        $this->load->model('common_model');
        
    } 

    /*
     * Listing of logo_images
     */
    function index()
    {
          $data['page_title'] = 'Logo Imgae';
        $data['logo_images'] = $this->Logo_image_model->get_all_logo_images();

        $this->load->view('logo_image/index',$data);
    }

    /*
     * Adding a new logo_image
     */
    function add()
    {   
          $data['page_title'] = 'Logo Imgae Adding';
  if($_FILES){
                //image upload parent_android
       $name=array();
       $j = 0;     // Variable for indexing uploaded image.
       $path =  FCPATH."uploads/logo_image/";;     // Declaring Path for uploaded images.
      for($i=0; $i<count($_FILES['file']['name']); $i++){
       $extension = explode('.', basename( $_FILES['file']['name'][$i]));
       //$path = $path . md5(uniqid()) . "." . $extension[count($extension)-1]; 
      $name=md5(uniqid()) . "." . $extension[count($extension)-1];
      $name1[]=$name;
      move_uploaded_file($_FILES['file']['tmp_name'][$i], $path.'/'.$name );
     
   }
//print_r($name1);


  $params = array(
				'p_logo_image_andriod' => $name1[0],
				'B_logo_image_andriod' => $name1[1],
				'p_logo_image_ios' => $name1[2],
				'B_logo_image_ios' => $name1[3],
            );
            
           $logo_image_id = $this->Logo_image_model->add_logo_image($params);
            //echo $this->db->last_query();
            redirect('logo_image/index');
        }
        else
        {
            $this->load->view('logo_image/add');
        }
    }  

    /*
     * Editing a logo_image
     */
    function edit($logo_id)
    {   
          $data['page_title'] = 'Logo Imgae Editing';
        // check if the logo_image exists before trying to edit it
        $data1= $this->Logo_image_model->get_logo_image($logo_id);
        $data['logo_image'] =$data1;
      
          if($_FILES)
             {
//               print_r($data1);
//        print_r($_FILES);
            //  print_r($_FILES);
              $name=array();
               $j = 0;     // Variable for indexing uploaded image.
              $path =  FCPATH."uploads/logo_image/";    // Declaring Path for uploaded images.
             // echo count($_FILES['file']['name']);
              for($i=0; $i<count($_FILES['file']['name']); $i++){
            //   echo $_FILES['file']['name'][$i];
                if(!empty($_FILES['file']['name'][$i])){
                  //  echo 'yes'.$i;
                    $extension = explode('.', basename( $_FILES['file']['name'][$i]));
                    $name=md5(uniqid()) . "." . $extension[count($extension)-1];
                   // echo $name;
                    $name1[$i]=$name;
                    move_uploaded_file($_FILES['file']['tmp_name'][$i], $path.'/'.$name );
                }
                else {
                   //echo 'no'.$i;
                    if($i==0)
                    {
                        $name1[$i]=$data1['p_logo_image_andriod'];
                    }
                     if($i==1)
                    {
                        $name1[$i]=$data1['B_logo_image_andriod'];
                    }
                     if($i==2)
                    {
                        $name1[$i]=$data1['p_logo_image_ios'];
                    }
                     if($i==3)
                    {
                        $name1[$i]=$data1['B_logo_image_ios'];
                    }
//                $name=md5(uniqid()) . "." . $extension[count($extension)-1];
//                $name1[$i]=$name;
                }
              }
                $params = array(
				'p_logo_image_andriod' => $name1[0],
				'B_logo_image_andriod' => $name1[1],
				'p_logo_image_ios' => $name1[2],
				'B_logo_image_ios' => $name1[3],
            );
//              print_r($name1);
                $this->Logo_image_model->update_logo_image($logo_id,$params);            
                redirect('logo_image/index');
        }
           else
            {
                $this->load->view('logo_image/edit',$data);
            }
        
       
    } 
    /*
     * Deleting logo_image
     */
    function remove($logo_id)
    {
        $logo_image = $this->Logo_image_model->get_logo_image($logo_id);

        // check if the logo_image exists before trying to delete it
        if(isset($logo_image['logo_id']))
        {
            $this->Logo_image_model->delete_logo_image($logo_id);
            redirect('logo_image/index');
        }
        else
            show_error('The logo_image you are trying to delete does not exist.');
    }
    
}
