<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Lsedit_app_user extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Lsedit_app_user_model');
           $this->load->model('User_model');
           if (!$this->User_model->auth_session()) {
            redirect('Login');
        }
    } 

    /*
     * Listing of lsedit_app_user
     */
    function index()
    {
         $data['page_title'] = 'LS EDIT APP USER';
        $data['lsedit_app_user'] = $this->Lsedit_app_user_model->get_all_lsedit_app_user();

        $this->load->view('lsedit_app_user/index',$data);
    }

    /*
     * Adding a new lsedit_app_user
     */
    function add()
    {   
          $data['page_title'] = 'LS EDIT APP USER Adding';
        $this->load->library('form_validation');

		$this->form_validation->set_rules('lsedit_user_name',' User Name','required');
		$this->form_validation->set_rules('lsedit_user_password','User Password','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'lsedit_user_name' => $this->input->post('lsedit_user_name'),
				'lsedit_user_password' => $this->input->post('lsedit_user_password'),
				
            );
            
            $lsedit_app_user_id = $this->Lsedit_app_user_model->add_lsedit_app_user($params);
            redirect('lsedit_app_user/index',$data);
        }
        else
        {
            $this->load->view('lsedit_app_user/add',$data);
        }
    }  

    /*
     * Editing a lsedit_app_user
     */
    function edit($lsedit_app_user_id)
    {   
           $data['page_title'] = 'LS EDIT APP USER Editing';
        // check if the lsedit_app_user exists before trying to edit it
        $data['lsedit_app_user'] = $this->Lsedit_app_user_model->get_lsedit_app_user($lsedit_app_user_id);
        
        $this->load->library('form_validation');

		$this->form_validation->set_rules('lsedit_user_name',' User Name','required');
		$this->form_validation->set_rules('lsedit_user_password','User Password','required');
		
		if($this->form_validation->run())     
                { 
                $params = array(
					'lsedit_user_name' => $this->input->post('lsedit_user_name'),
					'lsedit_user_password' => $this->input->post('lsedit_user_password'),
					
                );

                $this->Lsedit_app_user_model->update_lsedit_app_user($lsedit_app_user_id,$params);            
                redirect('lsedit_app_user/index');
            }
            else
            {
                $this->load->view('lsedit_app_user/edit',$data);
            }
        
        
    } 

    /*
     * Deleting lsedit_app_user
     */
    function remove($lsedit_app_user_id)
    {
        $lsedit_app_user = $this->Lsedit_app_user_model->get_lsedit_app_user($lsedit_app_user_id);

        // check if the lsedit_app_user exists before trying to delete it
        if(isset($lsedit_app_user['lsedit_app_user_id']))
        {
            $this->Lsedit_app_user_model->delete_lsedit_app_user($lsedit_app_user_id);
            redirect('lsedit_app_user/index');
        }
        else
            show_error('The lsedit_app_user you are trying to delete does not exist.');
    }
    
}
