<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Notification extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
         $this->load->model('Child_model');
        $this->load->model('Notification_model');
    } 

    /*
     * Listing of notification
     */
    function index()
    {
         $data['page_title'] = 'Notification';
         $data['child'] = $this->Child_model->get_all_child();
//        $data['notification'] = $this->Notification_model->get_all_notification();
         $data1 = $this->Notification_model->get_all_notification();
         for($j=0;$j<count($data1);$j++)
        {
        $child_id=$data1[$j]['n_child_id'];
        $child = $this->Child_model->get_child($child_id);
        $data1[$j]['n_child_id']=$child['child_name'];
        }
         $data['notification'] = $data1;
        $this->load->view('notification/index',$data);
    }

 function search()
    {  
     $data['page_title'] = 'Notification';
      $child_id= $this->input->get('child_id');
        $data['child'] = $this->Child_model->get_all_child();
       $data1 = $this->Notification_model->get_notification_by_child_id($child_id);
        for($j=0;$j<count($data1);$j++)
        {
        $child_id=$data1[$j]['n_child_id'];
        $child = $this->Child_model->get_child($child_id);
        $data1[$j]['n_child_id']=$child['child_name'];
        }
         $data['notification'] = $data1;
       $this->load->view('notification/index',$data);
    }
 
    
}
