<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Parent_app_user extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Parent_app_user_model');
         $this->load->library('pagination');
         $this->load->model('Child_model');
          $this->load->model('User_model');
           if (!$this->User_model->auth_session()) {
            redirect('Login');
        }
    } 

    /*
     * Listing of parent_app_user
     */
    function index($offset=0)
    {
         $data['page_title'] = 'Parent App Users';
         
         
         //pagination settings

      $config = array();
        $config["base_url"] = base_url() . "parent_app_user/index";
       $countval =$this->Parent_app_user_model->count();
     // print_r($countval);
        $config["total_rows"] =$countval;
       // echo $this->db->last_query();
        //    exit();
        $config["per_page"] = 100;
        $config["uri_segment"] = 3;

     $config['full_tag_open'] = "<ul class='pagination'>";
    $config['full_tag_close'] = '</ul>';
    $config['num_tag_open'] = '<li>';
    $config['num_tag_close'] = '</li>';
    $config['cur_tag_open'] = '<li class="active"><a href="#">';
    $config['cur_tag_close'] = '</a></li>';
    $config['prev_tag_open'] = '<li>';
    $config['prev_tag_close'] = '</li>';
    $config['first_tag_open'] = '<li>';
    $config['first_tag_close'] = '</li>';
    $config['last_tag_open'] = '<li>';
    $config['last_tag_close'] = '</li>';



    $config['prev_link'] = '<i class="fa fa-long-arrow-left"></i>Previous Page';
    $config['prev_tag_open'] = '<li>';
    $config['prev_tag_close'] = '</li>';


    $config['next_link'] = 'Next Page<i class="fa fa-long-arrow-right"></i>';
    $config['next_tag_open'] = '<li>';
    $config['next_tag_close'] = '</li>';


       $this->pagination->initialize($config); 

        $page = ($this->uri->segment(3)) ? $this->uri->segment(3) : 0;
          $data['list_num'] = $page;
          $data1 = $this->Parent_app_user_model->get_all_parent_app_user($config["per_page"], $page); 
for ($j = 0; $j < count($data1); $j++) {
            $fatheremail = $data1[$j]['child_father_email_id'];
          $countchildren = $this->Child_model->get_child_count($fatheremail);
             $child_name = $this->Child_model->get_child_names($fatheremail);
//           echo $this->db->last_query();
//           exit();
            $data1[$j]['names'] =$child_name;
          // echo $this->db->last_query();
           //  exit();
            $data1[$j]['count'] =$countchildren;
        }
         $data['parent_app_user']=$data1;
          $data['links']=$this->pagination->create_links();
         // print_r($data);
        $this->load->view('parent_app_user/index',$data);
    }

    
    
       function index_signedup($offset=0)
    {
         $data['page_title'] = 'Parent App Users';
         
         
         //pagination settings

      $config = array();
        $config["base_url"] = base_url() . "parent_app_user/index_signedup";
         $countval= $this->Parent_app_user_model->signedup_count();
          $data['signedup_count'] = $countval;
         $config["total_rows"]=$countval;
        $config["per_page"] = 100;
        $config["uri_segment"] = 3;

     $config['full_tag_open'] = "<ul class='pagination'>";
    $config['full_tag_close'] = '</ul>';
    $config['num_tag_open'] = '<li>';
    $config['num_tag_close'] = '</li>';
    $config['cur_tag_open'] = '<li class="active"><a href="#">';
    $config['cur_tag_close'] = '</a></li>';
    $config['prev_tag_open'] = '<li>';
    $config['prev_tag_close'] = '</li>';
    $config['first_tag_open'] = '<li>';
    $config['first_tag_close'] = '</li>';
    $config['last_tag_open'] = '<li>';
    $config['last_tag_close'] = '</li>';



    $config['prev_link'] = '<i class="fa fa-long-arrow-left"></i>Previous Page';
    $config['prev_tag_open'] = '<li>';
    $config['prev_tag_close'] = '</li>';


    $config['next_link'] = 'Next Page<i class="fa fa-long-arrow-right"></i>';
    $config['next_tag_open'] = '<li>';
    $config['next_tag_close'] = '</li>';


       $this->pagination->initialize($config); 

        $page = ($this->uri->segment(3)) ? $this->uri->segment(3) : 0;
          $data['list_num'] = $page;
    $data1 = $this->Parent_app_user_model->get_all_parent_app_user_signedup($config["per_page"], $page); 
    //  echo $this->db->last_query();
        for ($j = 0; $j < count($data1); $j++) {
            $fatheremail = $data1[$j]['child_father_email_id'];
            $countchildren = $this->Child_model->get_child_count($fatheremail);
            $child_name = $this->Child_model->get_child_names($fatheremail);
//           echo $this->db->last_query();
//           exit();
            $data1[$j]['names'] =$child_name;
            $data1[$j]['count'] =$countchildren;
        }
         $data['parent_app_user']=$data1;
          $data['links']=$this->pagination->create_links();
        //  print_r($data);
        $this->load->view('parent_app_user/index_signedup',$data);
    }
    
    
    /*
     * Adding a new parent_app_user
     */
    function add()
    {   
        $data['page_title'] = 'Adding';
        $data['direction']=$this->uri->segment(3);
        $direction=$this->uri->segment(3);
        $this->load->library('form_validation');

		$this->form_validation->set_rules('parent_app_user_name','Parent App User Name','required');
		$this->form_validation->set_rules('parent_app_user_password','Parent App User Password','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'parent_app_user_name' => $this->input->post('parent_app_user_name'),
				'parent_app_user_password' => $this->input->post('parent_app_user_password'),
				'parent_app_user_status' => '0',
            );
            
            $parent_app_user_id = $this->Parent_app_user_model->add_parent_app_user($params);
            
                if($direction=='notsignedup')
                {
                    redirect('parent_app_user/index');
                }
             else {
                 redirect('parent_app_user/index_signedup'); 
              }
//            redirect('parent_app_user/index',$data);
        }
        else
        {
            $this->load->view('parent_app_user/add',$data);
        }
    }  

    /*
     * Editing a parent_app_user
     */
    function edit($parent_app_user_id)
    {   
        $data['page_title'] = 'Editing';
         $data['direction']=$this->uri->segment(4);
        // check if the parent_app_user exists before trying to edit it
        $parent_app_user = $this->Parent_app_user_model->get_parent_app_user($parent_app_user_id);
        
        if(isset($parent_app_user['parent_app_user_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('parent_app_user_name','Parent App User Name','required');
			$this->form_validation->set_rules('parent_app_user_password','Parent App User Password','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'parent_app_user_name' => $this->input->post('parent_app_user_name'),
					'parent_app_user_password' => $this->input->post('parent_app_user_password'),
					'parent_app_user_status' => $this->input->post('parent_app_user_status'),
                );

                $this->Parent_app_user_model->update_parent_app_user($parent_app_user_id,$params);            
                $direction=$this->input->post('direction');
                if($direction=='notsignedup')
                {
                    redirect('parent_app_user/index');
                }
             else {
                 redirect('parent_app_user/index_signedup'); 
              }
                
            }
            else
            {   
                $data['parent_app_user'] = $this->Parent_app_user_model->get_parent_app_user($parent_app_user_id);
    
                $this->load->view('parent_app_user/edit',$data);
            }
        }
        else
            show_error('The parent_app_user you are trying to edit does not exist.');
    } 

    /*
     * Deleting parent_app_user
     */
    function remove($parent_app_user_id)
    {
         $data['page_title'] = 'Remove';
        $parent_app_user = $this->Parent_app_user_model->get_parent_app_user($parent_app_user_id);

        // check if the parent_app_user exists before trying to delete it
        if(isset($parent_app_user['parent_app_user_id']))
        {
            $this->Parent_app_user_model->delete_parent_app_user($parent_app_user_id);
             $direction=$this->uri->segment(4);
                if($direction=='notsignedup')
                {
                    redirect('parent_app_user/index');
                }
             else {
                 redirect('parent_app_user/index_signedup'); 
              }
                
        }
        else
            show_error('The parent_app_user you are trying to delete does not exist.');
    }
    
    
      function change_status()
    {
       $parent_app_user_id =  $this->uri->segment(3);
       $parent_app_user_status =  $this->uri->segment(4);
         if($parent_app_user_status==0)
         {
             $status=1;
         }
         else
         {
             $status=0;
         }
      // echo $status;
        // check if the child exists before trying to update it
        if($parent_app_user_id)
        {
           $this->Parent_app_user_model->status_parent($parent_app_user_id,$status);
           $this->session->set_flashdata('error', "User activated ,please check 'USERS SIGNED UP' list");
             redirect('parent_app_user/index');
        }
        else
            show_error('error.');
    }
    
         function change_status_notsigned()
    {
       $parent_app_user_id =  $this->uri->segment(3);
       $parent_app_user_status =  $this->uri->segment(4);
         if($parent_app_user_status==0)
         {
             $status=1;
         }
         else
         {
             $status=0;
         }
      // echo $status;
        // check if the child exists before trying to update it
        if($parent_app_user_id)
        {
           $this->Parent_app_user_model->status_parent($parent_app_user_id,$status);
             $this->session->set_flashdata('error', "User deactivated ,please check 'USERS NOT SIGNED UP' list");
             redirect('parent_app_user/index_signedup');
        }
        else
            show_error('error.');
    }
    
       function search() {
            $data['page_title'] = 'Search';
          $direction=$this->input->get('direction');
          $email = $this->input->get('email');
             $countval= $this->Parent_app_user_model->signedup_count();
          $data['signedup_count'] = $countval;
          
           $page = ($this->uri->segment(3)) ? $this->uri->segment(3) : 0;
          $data['list_num'] = $page;
          if($direction=='signedup')
          {
              $value=0;
          }
        else {
            $value=1;
        }
        
        
         $data1= $this->Parent_app_user_model->search($email,$value);
//         echo $this->db->last_query();
//            exit();
          for ($j = 0; $j < count($data1); $j++) {
            $fatheremail = $data1[$j]['child_father_email_id'];
          $countchildren = $this->Child_model->get_child_count($fatheremail);
           
             $child_name = $this->Child_model->get_child_names($fatheremail);
//           echo $this->db->last_query();
//           exit();
            $data1[$j]['names'] =$child_name;
            $data1[$j]['count'] =$countchildren;
        }
         $data['parent_app_user']=$data1;
         $data['links']=$this->pagination->create_links();
         
    
              if($direction=='notsignedup')
                {
                     $this->load->view('parent_app_user/index', $data);
                }
             else {
                $this->load->view('parent_app_user/index_signedup', $data);
             }
      }
}
