<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class School_attendance extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('School_attendance_model');
         $this->load->model('Setting_model');
        $this->load->library('pagination');
           $this->load->model('User_model');
           if (!$this->User_model->auth_session()) {
            redirect('Login');
        }
    } 

    
      /*
     * Listing of attendance
     */
    function index($offset=0)
    {
         $data['page_title'] = 'School Attendance';
        
        if($this->input->get('date'))
        {
            $date= $this->input->get('date');
            $date = date("Y-m-d", strtotime($date));
        }
        else {
            $date= date("Y-m-d");
        }
        
            //new change 09-05-2018
         $datecheck=date('Y-m-d', strtotime('-2 days'));
        $datetime=$datecheck.'60;60:60';
        if($date<$datetime)
        {
          $table_name='Copy_school_attendance';
        }
        else 
        {
         $table_name='School_attendance';       
        }
        
        
      // echo $date;
         //pagination----------------------

        $config = array();
        $config["base_url"] = base_url() . "School_attendance/index";
       $config["total_rows"] = $this->School_attendance_model->count_school_attendance($date,$table_name);
      //  $this->School_attendance_model->count_school_attendance($date,$table_name);
        //  echo $this->db->last_query(); exit();
        $config["per_page"] = 10;
        $config["uri_segment"] = 3;
        $config['full_tag_open'] = "<ul class='pagination'>";
        $config['full_tag_close'] = '</ul>';
        $config['num_tag_open'] = '<li>';
        $config['num_tag_close'] = '</li>';
        $config['cur_tag_open'] = '<li class="active"><a href="#">';
        $config['cur_tag_close'] = '</a></li>';
        $config['prev_tag_open'] = '<li>';
        $config['prev_tag_close'] = '</li>';
        $config['first_tag_open'] = '<li>';
        $config['first_tag_close'] = '</li>';
        $config['last_tag_open'] = '<li>';
        $config['last_tag_close'] = '</li>';
        $config['prev_link'] = '<i class="fa fa-long-arrow-left"></i>Previous Page';
        $config['prev_tag_open'] = '<li>';
        $config['prev_tag_close'] = '</li>';
        $config['next_link'] = 'Next Page<i class="fa fa-long-arrow-right"></i>';
        $config['next_tag_open'] = '<li>';
        $config['next_tag_close'] = '</li>';
        $this->pagination->initialize($config); 

        $page = ($this->uri->segment(3)) ? $this->uri->segment(3) : 0;
        $data['list_num'] = $page;
      //  echo $date.$page;
        $data['attendance'] = $this->School_attendance_model->get_all_school_attendance($date,$table_name,$config["per_page"], $page); 
        //echo $this->db->last_query(); exit();
        $data['links']=$this->pagination->create_links(); 
         
       //--------------------------
     $this->load->view('school_attendance/index_school_attendance',$data);
    }
    /*
     * Adding a new attendance
     */
  
//      public function save_download()
//  { 
//  $this->load->helper(array('My_Pdf'));   //  Load helper
// $data = file_get_contents(site_url('school_attendance/report_view')); // Pass the url of html report
// create_pdf($data); //Create pdf
// }
 
 
 public function pdf() {
       ini_set('memory_limit', '20M');
        if($this->input->get('date'))
        {
            $date= $this->input->get('date');
            $date = date("Y-m-d", strtotime($date));
        }
        else {
        $date= date("Y-m-d");
        }
         
            //new change 09-05-2018
         $datecheck=date('Y-m-d', strtotime('-2 days'));
        $datetime=$datecheck.'60;60:60';
        if($date<$datetime)
        {
          $table_name='Copy_school_attendance';
        }
        else 
        {
         $table_name='School_attendance';       
        }
        
        
       $data['attendance'] = $this->School_attendance_model->get_all_school_attendance_download_report($date,$table_name); 
       //echo $this->db->last_query(); exit();
       $html=  $this->load->view('school_attendance/pdf_school_attendance',$data,true);        
       $this->load->helper('dompdf');   
       pdf_create($html);     
      }
 
     function search_csv()
    {
         ini_set('memory_limit', '200M');
         $data_page['page_title'] = 'Report';
         $date1=$this->input->get('date');
         $date = date("Y-m-d", strtotime($date1));
         $settings = $this->Setting_model->get_all_settings();
        $la_time = new DateTimeZone('UTC');
        foreach ($settings as $key => $value) {
            $la_time = new DateTimeZone($value['timezone']);
        }
        
         $datecheck=date('Y-m-d', strtotime('-1 days'));
        $datetime=$datecheck.'60;60:60';
        if($date<$datetime)
        {
          $table_name='Copy_school_attendance';
        }
        else 
        {
         $table_name='School_attendance';       
        }
        
        $att_in = $this->School_attendance_model->get_all_school_attendance_download_in($date,$table_name);
        $att_out = $this->School_attendance_model->get_all_school_attendance_download_out($date,$table_name);
                 
   //echo $this->db->last_query(); exit(); 
        if($att_in=='' || $att_out=='')
        {
             $output = array('status' => 'NO Attendance'); 
        }
        else
        {
            
             for ($j = 0; $j < count($att_in); $j++) {
                $flag = true;
                for ($k = 0; $k < count($att_out); $k++) {

                    if (($att_out[$k]['at_child_id'] == $att_in[$j]['at_child_id'])) {
                        $att_in[$j]['at_child_out_time'] = $att_out[$k]['at_time_stamp'];
                        $flag = false;
                    }
                }
                if ($flag) {
                    $att_in[$j]['at_child_out_time'] = '';
                }
            }

           
     
        
            $result = $att_in;
            header("Content-type: application/csv");
            header("Content-Disposition: attachment; filename=\"BusList".".csv\"");
            header("Pragma: no-cache");
            header("Expires: 0");
            $handle = fopen('php://output', 'w'); 
            fputcsv($handle, array('#', 'Name', 'REG #', 'CLASS & SECTION', 'IN-Time', 'OUT-Time', 'DEVICE NAME'));
                          $i = 1;
                         foreach ($result as $data) {
                if ($data["at_child_out_time"] != '') {
                    //  $out_time = date('Y-m-d H:i:s', strtotime('+4 hour', strtotime($data["at_child_out_time"])));
                    $datetime = new DateTime($data["at_child_out_time"]);
                    $datetime->setTimezone($la_time);
                    $out_time = $datetime->format('Y-m-d H:i:s');
                    $out_time = date("H:i:s", strtotime($out_time));
                } else {
                    $out_time = '';
                }
                // $in_time = date('Y-m-d H:i:s', strtotime('+4 hour', strtotime($data["at_time_stamp"])));
                $datetime = new DateTime($data["at_time_stamp"]);
                $datetime->setTimezone($la_time);
                $in_time = $datetime->format('Y-m-d H:i:s');
                $in_time = date("H:i:s", strtotime($in_time));
                fputcsv($handle, array($i, $data["child_name"], $data["child_reg_no"], $data["child_class"] . '-' . $data["child_section"], date("H:i:s", strtotime($in_time)), $out_time, $data["device_name"]));
                $i++;
            }
             fclose($handle);
                          exit;
        }
         $this->load->view('school_attendance/report_csv',$data_page);
    }
    
        function report_csv()
    {
         $data['page_title'] = 'Report';
       $this->load->view('school_attendance/report_csv',$data);
    }
}
