<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Setting extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Setting_model');
        $this->load->model('Language_model');
           $this->load->model('User_model');
           if (!$this->User_model->auth_session()) {
            redirect('Login');
        }
    } 

    /*
     * Listing of settings
     */
    function index()
    {
        $data['page_title'] = 'Settings';
        $data['settings'] = $this->Setting_model->get_all_settings();

        $this->load->view('setting/index',$data);
    }

    /*
     * Adding a new setting
     */
    function add()
    {   
         $data['page_title'] = 'Add Settings';
        $this->load->library('form_validation');

		$this->form_validation->set_rules('set_sms','Set Sms','required');
		$this->form_validation->set_rules('set_push_notification','Set Push Notification','required');
		$this->form_validation->set_rules('set_nfc','Set Nfc','required');
		$this->form_validation->set_rules('set_calender','Set Calender','required');
		$this->form_validation->set_rules('set_notification','Set Notification','required');
		$this->form_validation->set_rules('set_attendance','Set Attendance','required');
		$this->form_validation->set_rules('set_other_features','Set Other Features','required');
		$this->form_validation->set_rules('set_track_school_bus','Set Track School Bus','required');
		$this->form_validation->set_rules('set_child_status','Set Child Status','required');
//		$this->form_validation->set_rules('set_status','Set Status','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'set_sms' => $this->input->post('set_sms'),
				'set_push_notification' => $this->input->post('set_push_notification'),
				'set_nfc' => $this->input->post('set_nfc'),
				'set_calender' => $this->input->post('set_calender'),
				'set_notification' => $this->input->post('set_notification'),
				'set_attendance' => $this->input->post('set_attendance'),
				'set_other_features' => $this->input->post('set_other_features'),
				'set_track_school_bus' => $this->input->post('set_track_school_bus'),
				'set_child_status' => $this->input->post('set_child_status'),
                
                                'school_latitude' => $this->input->post('school_latitude'),
				'school_longitude' => $this->input->post('school_longitude'),
				'supervisor_name' => $this->input->post('supervisor_name'),
				'supervisor_phone' => $this->input->post('supervisor_phone'),
                                'card_scan_type' => $this->input->post('card_scan_type'),
                                'set_auth_code' => $this->input->post('set_auth_code'),
                                'set_master_card_id' => $this->input->post('set_master_card_id'),
                                'set_OT_push' => $this->input->post('set_OT_push'),
//				'set_status' => $this->input->post('set_status'),
            );
            
            $setting_id = $this->Setting_model->add_setting($params);
            redirect('setting/index',$data);
        }
        else
        {
            $this->load->view('setting/add',$data);
        }
    }  

    /*
     * Editing a setting
     */
    function edit($set_id)
    {   
        $data['page_title'] = 'Edit Settings';
        // check if the setting exists before trying to edit it
        $setting = $this->Setting_model->get_setting($set_id);
        $data['languages'] = $this->Language_model->get_all_languages();
      //  echo $this->db->last_query();
        
        $rfc_1123_date = gmdate('D, d M Y H:i:s T', time()); 
        $datetime = new DateTime($rfc_1123_date);
        //echo $datetime->format('Y-m-d H:i:s') . "-------";
        $la_time = new DateTimeZone('Asia/Kolkata');
        $datetime->setTimezone($la_time);
        //echo $datetime->format('Y-m-d H:i:s');

        $tzlist = DateTimeZone::listIdentifiers(DateTimeZone::ALL);
         $data['time_list'] = $tzlist;
        
        
        if(isset($setting['set_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('set_sms','Set Sms','required');
			$this->form_validation->set_rules('set_push_notification','Set Push Notification','required');
			$this->form_validation->set_rules('set_nfc','Set Nfc','required');
			$this->form_validation->set_rules('set_calender','Set Calender','required');
			$this->form_validation->set_rules('set_notification','Set Notification','required');
			$this->form_validation->set_rules('set_attendance','Set Attendance','required');
			$this->form_validation->set_rules('set_other_features','Set Other Features','required');
			$this->form_validation->set_rules('set_track_school_bus','Set Track School Bus','required');
			$this->form_validation->set_rules('set_child_status','Set Child Status','required');
//			$this->form_validation->set_rules('set_status','Set Status','required|integer');
		
			if($this->form_validation->run())     
            {   
                            
                     if($this->input->post('set_language')){
                         
                         $details = $this->Language_model->get_language_details($this->input->post('set_language'));
                       //  print_r($details); exit();
                     }else {
                            $details['lang_native']="";
                            $details['lang_align_type']="";
                            $details['lang_code']="";
                     }       
                            
                     if($this->input->post('language1')){
                         
                         $details_lang1 = $this->Language_model->get_language_details($this->input->post('language1'));
                       //  print_r($details); exit();
                     }else {
                            $details_lang1['lang_native']="";
                            $details_lang1['lang_align_type']="";
                            $details_lang1['lang_code']="";
                     }       
                            
                $params = array(
					'set_sms' => $this->input->post('set_sms'),
					'set_push_notification' => $this->input->post('set_push_notification'),
					'set_nfc' => $this->input->post('set_nfc'),
					'set_calender' => $this->input->post('set_calender'),
					'set_notification' => $this->input->post('set_notification'),
					'set_attendance' => $this->input->post('set_attendance'),
					'set_other_features' => $this->input->post('set_other_features'),
					'set_track_school_bus' => $this->input->post('set_track_school_bus'),
					'set_child_status' => $this->input->post('set_child_status'),
                                        'school_latitude' => $this->input->post('school_latitude'),
                                        'school_longitude' => $this->input->post('school_longitude'),
                                        'supervisor_name' => $this->input->post('supervisor_name'),
                                        'supervisor_phone' => $this->input->post('supervisor_phone'),
//					'set_status' => $this->input->post('set_status'),
                                        'card_scan_type' => $this->input->post('card_scan_type'),
                                        'set_auth_code' => $this->input->post('set_auth_code'),
                                        'set_master_card_id' => $this->input->post('set_master_card_id'),
                                        'timezone' => $this->input->post('timezone'),
                                        'truncate' => $this->input->post('truncate'),
                                        'set_language' => $this->input->post('set_language'),
                                        'set_lang_native' => $details['lang_native'],
                                        'set_lang_align_type' => $details['lang_align_type'],
                                        'set_lang_code' => $details['lang_code'],
                                        'set_language1' => $this->input->post('language1'),
                                        'set_lang1_native' => $details_lang1['lang_native'],
                                        'set_lang1_align_type' => $details_lang1['lang_align_type'],
                                        'set_lang1_code' => $details_lang1['lang_code'],
                                        'set_OT_push' => $this->input->post('set_OT_push'),
                );

                $this->Setting_model->update_setting($set_id,$params);            
                redirect('setting/index');
            }
            else
            {   
                $data['setting'] = $this->Setting_model->get_setting($set_id);
    
                $this->load->view('setting/edit',$data);
            }
        }
        else
            show_error('The setting you are trying to edit does not exist.');
    } 

    /*
     * Deleting setting
     */
    function remove($set_id)
    {
        $data['page_title'] = 'Remove Settings';
        $setting = $this->Setting_model->get_setting($set_id);

        // check if the setting exists before trying to delete it
        if(isset($setting['set_id']))
        {
            $this->Setting_model->delete_setting($set_id);
            redirect('setting/index');
        }
        else
            show_error('The setting you are trying to delete does not exist.');
    }
    
  function change_status()
    {
      $set_id =  $this->uri->segment(3);
      $set_status =  $this->uri->segment(4);
         if($set_status==0)
         {
             $status=1;
         }
         else
         {
             $status=0;
         }
      // echo $status;
        // check if the child exists before trying to update it
        if($set_id)
        {
           $this->Setting_model->status_setting_model($set_id,$status);
            redirect('setting/index');
        }
        else
            show_error('The child you are trying to delete does not exist.');
    }  
}
