<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Supervisor extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
         $this->load->model('Bu_model');
         $this->load->model('Trip_model');
         $this->load->model('Attendance_model');
         $this->load->model('Child_model');
          $this->load->model('User_model');
           if (!$this->User_model->auth_session()) {
            redirect('Login');
        }
    } 

    /*
     * Listing of push_msg_map
     */
    function index()
    {
        $data=array();
        $running_satus='running';
        $data['bus_list'] = $this->Bu_model->get_bus_by_running_status($running_satus);
        $i=0;
        $this->load->helper('map');
       
        foreach ($data['bus_list'] as $key => $bus) {
           
           $trip_details=$this->Trip_model->get_trip($bus['bus_current_trip_id']);        
           $attendance=$this->Attendance_model->get_attendance_count_by_bus_id($bus['bus_id'],$bus['bus_current_trip_id'],$bus['bus_child_pickup_or_drop_off']);
         // echo $this->db->last_query();exit();
           $total_child_list_count=$this->Child_model->get_total_count_child_trip($bus['bus_current_trip_id']);
            $data['bus_list'][$i]['trip_name']=$trip_details['trip_desc'];
            $data['bus_list'][$i]['trip_pickedup']=$attendance['count'];
            $data['bus_list'][$i]['trip_total_no']=$total_child_list_count['count'];
           // $school_lati="24.445445";
           // $school_longi="54.409714";
            
            $school_lati=  "9.959855"; 
            $school_longi="76.289505";          
           $tracking= $this->Attendance_model->last_known_location_by_busn_id($bus['bus_id'],$bus['bus_current_trip_id']);
            $data['bus_list'][$i]['distance']=distance($school_lati, $school_longi, $tracking['tracking_lati'], $tracking['tracking_logi'], "K");
             $data['bus_list'][$i]['distance'] = round( $data['bus_list'][$i]['distance'], 1);
            $i++;
        }
        $this->load->view('supervisor/supervisor',$data);
    }

    
    
}
