<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Supervisor_app_user extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Supervisor_app_user_model');
           $this->load->model('User_model');
           if (!$this->User_model->auth_session()) {
            redirect('Login');
        }
    } 

    /*
     * Listing of supervisor_app_user
     */
    function index()
    {
         $data['page_title'] = 'Supervisor App Users';
        $data['supervisor_app_user'] = $this->Supervisor_app_user_model->get_all_supervisor_app_user();

        $this->load->view('supervisor_app_user/index',$data);
    }

    /*
     * Adding a new supervisor_app_user
     */
    function add()
    {   
          $data['page_title'] = ' Supervisor App Users Adding';
           $this->load->library('form_validation');

		$this->form_validation->set_rules('supervisor_user_name',' User Name','required');
		$this->form_validation->set_rules('supervisor_user_password','User Password','required');
		
		if($this->form_validation->run())     
        {
          $params = array(
				'supervisor_user_name' => $this->input->post('supervisor_user_name'),
				'supervisor_user_password' => $this->input->post('supervisor_user_password'),
				
            );
            
            $supervisor_app_user_id = $this->Supervisor_app_user_model->add_supervisor_app_user($params);
            redirect('supervisor_app_user/index',$data);
        }
        else
        {
            $this->load->view('supervisor_app_user/add',$data);
        }
    }  

    /*
     * Editing a supervisor_app_user
     */
    function edit($supervisor_app_user_id)
    {   
             $data['page_title'] = ' Supervisor App Users Editing';
              // check if the supervisor_app_user exists before trying to edit it
              $data['supervisor_app_user'] = $this->Supervisor_app_user_model->get_supervisor_app_user($supervisor_app_user_id);
               $this->load->library('form_validation');

		$this->form_validation->set_rules('supervisor_user_name',' User Name','required');
		$this->form_validation->set_rules('supervisor_user_password','User Password','required');
		
		if($this->form_validation->run())     
             {
        
        
                $params = array(
					'supervisor_user_name' => $this->input->post('supervisor_user_name'),
					'supervisor_user_password' => $this->input->post('supervisor_user_password'),
					
                );

                $this->Supervisor_app_user_model->update_supervisor_app_user($supervisor_app_user_id,$params);            
                redirect('supervisor_app_user/index');
            }
            else
            {
                $this->load->view('supervisor_app_user/edit',$data);
            }
       
    } 

    /*
     * Deleting supervisor_app_user
     */
    function remove($supervisor_app_user_id)
    {
        $supervisor_app_user = $this->Supervisor_app_user_model->get_supervisor_app_user($supervisor_app_user_id);

        // check if the supervisor_app_user exists before trying to delete it
        if(isset($supervisor_app_user['supervisor_app_user_id']))
        {
            $this->Supervisor_app_user_model->delete_supervisor_app_user($supervisor_app_user_id);
            redirect('supervisor_app_user/index');
        }
        else
            show_error('The supervisor_app_user you are trying to delete does not exist.');
    }
    
}
