<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Touch extends CI_Controller
{
    function __construct()
    {
         parent::__construct();
        $this->load->model('Trip_model');
        $this->load->model('Bu_model');
        $this->load->model('Bus_app_user_model');
        $this->load->model('Parent_app_user_model');
        $this->load->model('Child_model');
        $this->load->model('Tracking_model');
        $this->load->model('Attendance_model');
        $this->load->model('Push_msg_map_model');
        $this->load->model('Notification_model');
        $this->load->model('common_model');
        $this->load->model('Finish_trip_detail_model');
        $this->load->model('Logo_image_model');
           $this->load->model('User_model');
           if (!$this->User_model->auth_session()) {
            redirect('Login');
        }
    } 

    /*
     * Listing of notification
     */
    function index()
    {
         $data['page_title'] = 'Touch';
         $data['bus'] = $this->Bu_model->get_all_bus();
        // $data['trip_num']  = $this->Trip_model->get_trip_with_bus_id_index('1');
         $this->load->view('touch/index',$data);
    }

 public function pdf() {
     
      $data['page_title'] = 'Report';
     $data['bus'] = $this->Bu_model->get_all_bus();
    $date=$this->input->get('date');
    $time_stamp= date('Y-m-d', strtotime($date));
    
        $bus_id=$this->input->get('bus');
        $trip_id= $this->input->get('trip');
        //.........................................................................
        $data['bus_name']= $this->Bu_model->get_bu($bus_id);
        $data['trip']= $this->Trip_model->get_trip($trip_id);

       $child_id = $this->Attendance_model->get_child_id_from_attandence($trip_id,$time_stamp);  
//       echo count($child_id);
//              echo $this->db->last_query();exit();
//       $data = $this->Child_model->get_child_name(1); 
//            echo $this->db->last_query();exit();
//            
       for($i=1;$i<=count($child_id);$i++)
       {
        $data1[]= $this->Child_model->get_child_details($i); 
        // echo $this->db->last_query();exit();
       }
       $data['child_details']=$data1;
   
  // echo $this->db->last_query();exit();
     
    $html=  $this->load->view('touch/view_pdf',$data,true);     
    $this->load->helper('dompdf');   
     pdf_create($html);

 }

 
}
