<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Tracking extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tracking_model');
        $this->load->model('Bu_model');
        $this->load->model('Trip_model');
        $this->load->model('Child_model');
        $this->load->library('pagination');
           $this->load->model('User_model');
           if (!$this->User_model->auth_session()) {
            redirect('Login');
        }
    } 

    /*
     * Listing of tracking
     */
    function index($offset=0)
    {
        $data['page_title'] = 'Tracking';
//        $data['tracking'] = $this->Tracking_model->get_all_tracking();
        $data['bus'] = $this->Bu_model->get_all_bus();
//        $data['trip'] = $this->Tracking_model->get_all_trips();
        $data['trip_num']  = $this->Trip_model->get_trip_with_bus_id_index('1');
  
        
         //pagination settings

      $config = array();
        $config["base_url"] = base_url() . "tracking/index";
        $config["total_rows"] = $this->Tracking_model->count();
        $config["per_page"] = 20;
        $config["uri_segment"] = 3;

     $config['full_tag_open'] = "<ul class='pagination'>";
    $config['full_tag_close'] = '</ul>';
    $config['num_tag_open'] = '<li>';
    $config['num_tag_close'] = '</li>';
    $config['cur_tag_open'] = '<li class="active"><a href="#">';
    $config['cur_tag_close'] = '</a></li>';
    $config['prev_tag_open'] = '<li>';
    $config['prev_tag_close'] = '</li>';
    $config['first_tag_open'] = '<li>';
    $config['first_tag_close'] = '</li>';
    $config['last_tag_open'] = '<li>';
    $config['last_tag_close'] = '</li>';



    $config['prev_link'] = '<i class="fa fa-long-arrow-left"></i>Previous Page';
    $config['prev_tag_open'] = '<li>';
    $config['prev_tag_close'] = '</li>';


    $config['next_link'] = 'Next Page<i class="fa fa-long-arrow-right"></i>';
    $config['next_tag_open'] = '<li>';
    $config['next_tag_close'] = '</li>';


    $this->pagination->initialize($config); 

        $page = ($this->uri->segment(3)) ? $this->uri->segment(3) : 0;
          $data['list_num'] = $page;
        $data1  = $this->Tracking_model->get_all_tracking($config["per_page"], $page); 
    
    for($j=0;$j<count($data1);$j++)
    {
       $tracking_bus_id=$data1[$j]['tracking_bus_id'];
       $bus_number = $this->Bu_model->get_bu($tracking_bus_id);
       $data1[$j]['tracking_bus_id']=$bus_number['bus_name'];
       //trip
       $tracking_trip_id=$data1[$j]['tracking_trip_id'];
       $trip_number_off = $this->Trip_model->get_trip($tracking_trip_id);
       $data1[$j]['tracking_trip_id']=$trip_number_off['trip_no'];
     }
    $data['tracking']=$data1;
    
         $data['links']=$this->pagination->create_links();
        $this->load->view('tracking/index',$data);

   
//-----------------
        
        
    }

    /*
     * Adding a new tracking
     */
    function add()
    {   
         $data['page_title'] = 'Add Tracking';
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tracking_logi' => $this->input->post('tracking_logi'),
				'tracking_lati' => $this->input->post('tracking_lati'),
				'tracking_trip_id' => $this->input->post('tracking_trip_id'),
				'tracking_bus_id' => $this->input->post('tracking_bus_id'),
				'tracking_time_stamp' => $this->input->post('tracking_time_stamp'),
				'tracking_time_stamp_device' => $this->input->post('tracking_time_stamp_device'),
				'tracking_battery_status' => $this->input->post('tracking_battery_status'),
				'tracking_data_type' => $this->input->post('tracking_data_type'),
            );
            
            $tracking_id = $this->Tracking_model->add_tracking($params);
            redirect('tracking/index');
        }
        else
        {
            $this->load->view('tracking/add',$data);
        }
    }  

    /*
     * Editing a tracking
     */
   function edit($tracking_id)
    {   
        $data['page_title'] = 'Edit Tracking';
        // check if the tracking exists before trying to edit it
        $tracking = $this->Tracking_model->get_tracking($tracking_id);
        
        if(isset($tracking['tracking_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tracking_logi' => $this->input->post('tracking_logi'),
					'tracking_lati' => $this->input->post('tracking_lati'),
					'tracking_trip_id' => $this->input->post('tracking_trip_id'),
					'tracking_bus_id' => $this->input->post('tracking_bus_id'),
					'tracking_time_stamp' => $this->input->post('tracking_time_stamp'),
					'tracking_time_stamp_device' => $this->input->post('tracking_time_stamp_device'),
					'tracking_battery_status' => $this->input->post('tracking_battery_status'),
					'tracking_data_type' => $this->input->post('tracking_data_type'),
                );

                $this->Tracking_model->update_tracking($tracking_id,$params);            
                redirect('tracking/index');
            }
            else
            {   
                $data['tracking'] = $this->Tracking_model->get_tracking($tracking_id);
    
                $this->load->view('tracking/edit',$data);
            }
        }
        else
            show_error('The tracking you are trying to edit does not exist.');
    } 

    /*
     * Deleting tracking
     */
 function remove($tracking_id)
    {
     $data['page_title'] = 'Delete Tracking';
        $tracking = $this->Tracking_model->get_tracking($tracking_id);

        // check if the tracking exists before trying to delete it
        if(isset($tracking['tracking_id']))
        {
            $this->Tracking_model->delete_tracking($tracking_id);
            redirect('tracking/index');
        }
        else
            show_error('The tracking you are trying to delete does not exist.');
    }
   function search($offset=0)
    {
        $data['page_title'] = 'Tracking';
      $data['trip_num']  = $this->Trip_model->get_trip_with_bus_id_index('1');
        $data['bus'] = $this->Bu_model->get_all_bus();
//        print_r($_GET);
            if(isset($_GET) && count($_GET) > 0)     
            {   
                
            $tracking_time_stamp= $this->input->get('date');
            $tracking_bus_id=$this->input->get('bus');
            $tracking_trip_id= $this->input->get('trip');

                                        
 //pagination------------------
                                        
                                        
                                        
    $config = array();
    $config["base_url"] = base_url() . 'tracking/search';
    $val=$this->Tracking_model->count_search($tracking_trip_id,$tracking_bus_id,$tracking_time_stamp);
    $config["total_rows"] =  sizeof($val);
       // echo $this->db->last_query();
    $config["per_page"] = 20;
    $config["uri_segment"] = 3;
    $config['enable_query_strings'] = TRUE;
    $config['reuse_query_string'] = TRUE;
    $config['query_string_segment'] =  '?date='.$tracking_time_stamp.'&bus='.$tracking_bus_id.'&trip='.$tracking_trip_id;  
    $config['full_tag_open'] = "<ul class='pagination'>";
    $config['full_tag_close'] = '</ul>';
    $config['num_tag_open'] = '<li>';
    $config['num_tag_close'] = '</li>';
    $config['cur_tag_open'] = '<li class="active"><a href="#">';
    $config['cur_tag_close'] = '</a></li>';
    $config['prev_tag_open'] = '<li>';
    $config['prev_tag_close'] = '</li>';
    $config['first_tag_open'] = '<li>';
    $config['first_tag_close'] = '</li>';
    $config['last_tag_open'] = '<li>';
    $config['last_tag_close'] = '</li>';
    $config['prev_link'] = '<i class="fa fa-long-arrow-left"></i>Previous Page';
    $config['prev_tag_open'] = '<li>';
    $config['prev_tag_close'] = '</li>';
    $config['next_link'] = 'Next Page<i class="fa fa-long-arrow-right"></i>';
    $config['next_tag_open'] = '<li>';
    $config['next_tag_close'] = '</li>';
    //$config['suffix'] = '?date='.$tracking_time_stamp.'&bus='.$tracking_bus_id.'&trip='.$tracking_trip_id;     

    $this->pagination->initialize($config);
     $page = ($this->uri->segment(3)) ? $this->uri->segment(3) : 0;
          $data['list_num'] = $page;
         $data['tracking'] = $this->Tracking_model->search_tracking($tracking_trip_id,$tracking_bus_id,$tracking_time_stamp,$config["per_page"], $page); 
        //  echo $this->db->last_query();
          $data['links']=$this->pagination->create_links();
        $this->load->view('tracking/index',$data);
                                        
      //-----------------


            }
       
    }
    
          function map()
    {
        $data['page_title'] = 'Maping';
        $bus_list=$this->Bu_model->get_all_bus();
        $data['bus'] = $bus_list;
        $data['trip_num']  = $this->Trip_model->get_trip_with_bus_id_index($bus_list[0]['bus_id']);
          if(  $this->input->post('bus'))     
            {   
            $tracking_time_stamp=date("Y/m/d");
            $tracking_time_stamp= $this->input->post('date');
            $tracking_bus_id=$this->input->post('bus');
            $tracking_trip_id= $this->input->post('trip');
            $data['tracking_map'] = $this->Tracking_model->search_tracking($tracking_trip_id,$tracking_bus_id,$tracking_time_stamp); 
            }
            $this->load->view('tracking/map',$data); 


     
    }
    /*   function map_search()
    {
        $data['page_title'] = 'Maping';

       
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $tracking_time_stamp=date("Y/m/d");
                $tracking_time_stamp= $this->input->post('date');
                $tracking_bus_id=$this->input->post('bus');
                $tracking_trip_id= $this->input->post('trip');

              $data['tracking_map'] = $this->Tracking_model->search_tracking($tracking_trip_id,$tracking_bus_id,$tracking_time_stamp);
               echo $this->db->last_query();
             //  print_r($data);
            $data['trip_num']  = $this->Trip_model->get_trip_with_bus_id_index('1');
//             echo $this->db->last_query();
//             exit();
            //  $data['bus'] = $this->Bu_model->get_all_bus();
             // $data['trip'] = $this->Tracking_model->get_all_trips();
             $this->load->view('tracking/map',$data); 
            }else {
               redirect('tracking/map');  
            }
    }*/
     function getmap()
    {
          $id                = $this->input->postdata('id');
          $oldLat            = $this->input->postdata('oldLat');
          $oldLog            = $this->input->postdata('oldLog');
       $tracking_time_stamp  = $this->input->post('date');
          $tracking_bus_id   =$this->input->post('bus_id');
          $tracking_trip_id  = $this->input->post('trip_id');
          $data['tracking']  = $this->Tracking_model->get_tracking_map($id,$oldLat);
        // echo $this->db->last_query();
     //  $data['page_title'] = 'Maping';
       
       // $data['tracking'] = $this->Tracking_model->get_tracking_map($tracking_trip_id,$tracking_bus_id,$tracking_time_stamp);
       // $this->load->view('tracking/getmap',$data);    
       
    }
    
         function ajax_list_index($id)
    {
             
          $data['trip_num']  = $this->Trip_model->get_trip_with_bus_id_index($id);
          $this->load->view('tracking/get_trip_num_index',$data); 
    }
          function ajax_list_Report($id)
    {
              if($id=='All')
              {
                  $data['trip_num']='All';
              }
              else
              {
          $data['trip_num']  = $this->Trip_model->get_trip_with_bus_id_index($id);
              }
//        echo $this->db->last_query();
          $this->load->view('tracking/get_trip_num_index',$data); 
    }
 
    
        function ajax_list($id)
    {
          $data['trip_num']  = $this->Trip_model->get_trip_with_bus_id($id);
         //echo $this->db->last_query();
          $this->load->view('tracking/get_trip_num',$data); 
    }
    
    function next_lat_lon()
    {
            $tracking_time_stamp=date("Y/m/d");
            //    $tracking_time_stamp="2017/02/06";
            $tracking_bus_id=$this->input->post('value_bus_id');
            $tracking_trip_id= $this->input->post('value_trip_id');
            $size= $this->input->post('size');
            $data['size']= $this->input->post('size');
            $data['lat']= $this->input->post('oldLat');
            $data['lon']= $this->input->post('oldLog');
//             $oldLat= $this->input->post('oldLat');
//            $oldLog= $this->input->post('oldLog');
            $data['tracing_values']  = $this->Tracking_model->get_new_lat_lon_with_id($tracking_trip_id,$tracking_bus_id,$tracking_time_stamp,$size);
            $data['tracing_values_back']  = $this->Tracking_model->get_new_lat_lon_with_id_back($tracking_trip_id,$tracking_bus_id,$tracking_time_stamp,$size);
         // echo $this->db->last_query();
            $this->load->view('tracking/get_new_lat_lon',$data); 
    }
    
    
        /*
     * map ios
     */

           function map_search_ios()
    {
             $data1=$this->input->get('bus_id');
            $data2=  $this->input->get('child_id');
            $data['page_title'] = 'Maping';
            $trip_id_details = $this->Trip_model->get_trip_with_bus_id($data1);
             $data['bus_id_map'] =$data1;
            $data['trip_id_map'] =$trip_id_details['bus_current_trip_id'];
            
            $data['child_trip_id_details'] = $this->Child_model->get_child_with_trip_id($data2,$data1);
          //  echo $this->db->last_query();exit();
            if($data1)    
            {   
            $tracking_time_stamp=date("Y/m/d");
            $data['tracking_map'] = $this->Tracking_model->search_tracking($trip_id_details['bus_current_trip_id'],$data1,$tracking_time_stamp);
            
           // echo $this->db->last_query();exit();
            $data['bus'] = $this->Bu_model->get_all_bus();
            $this->load->view('tracking/map_ios',$data); 
            }
    }
    
     /*
     * map android
     */

           function map_search_android()
    {
            $data1=$this->input->get('bus_id');
            $data2=  $this->input->get('child_id');

            $data['page_title'] = 'Maping';
            $trip_id_details = $this->Trip_model->get_trip_with_bus_id($data1);
            $data['bus_id_map'] =$data1;
            $data['trip_id_map'] =$trip_id_details['bus_current_trip_id'];
            $data['child_trip_id_details'] = $this->Child_model->get_child_with_trip_id($data2,$data1);
            if($data1)    
            {   
           $tracking_time_stamp=date("Y/m/d");
             //    $tracking_time_stamp="2017/02/06";
            $data['tracking_map'] = $this->Tracking_model->search_tracking($trip_id_details['bus_current_trip_id'],$data1,$tracking_time_stamp);
//            echo $this->db->last_query();exit();
            $data['bus'] = $this->Bu_model->get_all_bus();
           
            $this->load->view('tracking/map_android',$data); 
            }
    }
    
         /*
     * map supervisor
     */

           function map_supervisor()
    {
            $data1=$this->input->get('bus_id');
//            $data2=  $this->input->get('child_id');

            $data['page_title'] = 'Maping';
            $bus_details = $this->Bu_model->get_bu($data1);
          //   echo $this->db->last_query();exit();
            $data['bus_id_map'] =$data1;
            $data['trip_id_map'] =$bus_details['bus_current_trip_id'];
//            $data['child_trip_id_details'] = $this->Child_model->get_child_with_trip_id($data2,$data1);
            if($data1)    
            {   
           $tracking_time_stamp=date("Y/m/d");
             //    $tracking_time_stamp="2017/02/06";
            $data['tracking_map'] = $this->Tracking_model->search_tracking($bus_details['bus_current_trip_id'],$data1,$tracking_time_stamp);
           //  echo $this->db->last_query();exit();
             $this->load->view('tracking/map_supervisor',$data); 
            }
    }
        
 
}
