<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Web_view extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tracking_model');
        $this->load->model('Bu_model');
        $this->load->model('Trip_model');
        $this->load->model('Child_model');
        $this->load->library('pagination');
           $this->load->model('User_model');
           if (!$this->User_model->auth_session()) {
            redirect('Login');
        }
    } 
     
     /*
     * contact
     */

     function contact_android()
    {
            $child_id=  $this->input->get('child_id');
            $data['page_title'] = 'Contact';
            $data['child_details'] = $this->Child_model->get_child($child_id);
           //echo $this->db->last_query();exit();
            $this->load->view('web_view/contact_android',$data); 
    }
         function contact_ios()
    {
            $child_id=  $this->input->get('child_id');
            $data['page_title'] = 'Contact';
            $data['child_details'] = $this->Child_model->get_child($child_id);
           //echo $this->db->last_query();exit();
            $this->load->view('web_view/contact_ios',$data); 
    }
    
       function contact_lang1()
    {
            $child_id=  $this->input->get('child_id');
            $data['page_title'] = 'Contact';
            $data['child_details'] = $this->Child_model->get_child($child_id);
           //echo $this->db->last_query();exit();
            $this->load->view('web_view/contact_lang1',$data); 
    }
       /*
     * contact Email
     */
 public function send_mail() { 
$data['page_title'] = 'Contact';
$to = 'online@dunamisworld.com';
//$to = 'anoop@dunamisworld.com';
//$from = 'info@dunamisworld.com';
$from = $this->input->post('child_father_email_id');
$subject = 'Parent App Feedback.'.SCHOOL_SHORT_NAME;


$message = '
<html>
<head>
</head>
<body>
 <b>Child name</b>:'.$this->input->post('child_name').
'<br/><b>Child Class</b>:'.$this->input->post('child_class').
'<br/><b>Child Section</b>:'.$this->input->post('child_section').
'<br/><b>Child Father Name</b>:'.$this->input->post('child_father_name').
'<br/><b>Child Father Email</b>:'.$this->input->post('child_father_email_id').
'<br/><b>Child Father Phone</b>:'.$this->input->post('child_father_tel').
'<br/><b>Child Mother Phone</b>:'.$this->input->post('child_mother_tel').
'<br/><b>Child Home Phone</b>:'.$this->input->post('child_home_tel').
'<br/><b>Questions</b>
<br/><b>How useful do you find this application?</b>:'.$this->input->post('useful').  
'<br/><b>Are you satisfied with the information displayed in the map?</b>:'.$this->input->post('information').
'<br/><b>Are you satisfied with the design of the Application?</b>:'.$this->input->post('design').
'<br/><b>Message</b>:'.$this->input->post('Field4').
'<br/><b>Did you find inaccuracies in the Application?</b>:'.$this->input->post('inaccuracies').
'<br/><b>What improvements would you like to see in this application?</b>:'.$this->input->post('improvements').
'<br/><b>ould you like us to call you regarding improvements to this Application?</b>:'.$this->input->post('call').
'</body>
</html>
';
$headers = "MIME-Version: 1.0\r\n"; 
$headers .= "Content-type: text/html; charset=iso-8859-1\r\n"; 
$headers  .= "From:$from\r\n"; 
$mail=mail($to, $subject, $message, $headers)or die("mail error");
if($mail)
{
    echo "Your feedback has been received ,Thank You";
}
    }
    
    
      function otp()
    {
             $data['page_title'] = 'otp';
              $this->load->view('web_view/otp',$data); 
    }
       function password()
    {
             $data['page_title'] = 'password';
              $this->load->view('web_view/password',$data); 
    }
}
