<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Access_log_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get access_log by alog_id
     */
    function get_access_log($alog_id)
    {
        return $this->db->get_where('Access_log',array('alog_id'=>$alog_id))->row_array();
    }
        
    /*
     * Get all access_log
     */
    function get_all_access_log($limit=null,$offset=NULL)
    {
        $this->db->order_by('alog_id', 'desc');
        $this->db->limit($limit, $offset);
        return $this->db->get('Access_log')->result_array();
    }
      
     public function count()
       {
           $this->db->from('Access_log');
          return $this->db->count_all_results();
       }
    /*
     * function to add new access_log
     */
    function add_access_log($params)
    {
        $this->db->insert('Access_log',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update access_log
     */
    function update_access_log($alog_id,$params)
    {
        $this->db->where('alog_id',$alog_id);
        return $this->db->update('Access_log',$params);
    }
    
    /*
     * function to delete access_log
     */
    function delete_access_log($alog_id)
    {
        return $this->db->delete('Access_log',array('alog_id'=>$alog_id));
    }
    
    
       function count_log()
    {
        return $this->db->query("SELECT alog_os_version,alog_device,`alog_model`, COUNT(*) AS num FROM Access_log GROUP BY `alog_model` ORDER BY num DESC LIMIT 5")->result_array();
    }
       function count_devices()
    {
       $this->db->from('Access_log');
        return $this->db->count_all_results();
    }
}
