<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Attendance_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get attendance by at_id
     */
    function get_attendance($at_id)
    {
        return $this->db->get_where('Attendance',array('at_id'=>$at_id))->row_array();
    }
    
    /*
     * Get all attendance
     */
    function get_all_attendance($limit=null,$offset=NULL)
    {
         $this->db->limit($limit, $offset);
        return $this->db->get('Attendance')->result_array();
    }
    
    /*
     * function to add new attendance
     */
    function add_attendance($params)
    {
        $this->db->insert('Attendance',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update attendance
     */
    function update_attendance($at_id,$params)
    {
        $this->db->where('at_id',$at_id);
        $response = $this->db->update('Attendance',$params);
        if($response)
        {
            return "attendance updated successfully";
        }
        else
        {
            return "Error occuring while updating attendance";
        }
    }
    
    /*
     * function to delete attendance
     */
    function delete_attendance($at_id)
    {
        $response = $this->db->delete('Attendance',array('at_id'=>$at_id));
        if($response)
        {
            return "attendance deleted successfully";
        }
        else
        {
            return "Error occuring while deleting attendance";
        }
    }
    
    function get_total_morning_section_attendance($child_id) {
               
        $this->db->select('COUNT(*) as count');
        $this->db->where('at_child_id',$child_id);
        $this->db->where('at_trip_type','pickup');
        $this->db->where('at_pickup_or_drop_off','pickup');
        $this->db->where('at_child_status','present');
        $row=$this->db->get('Attendance')->row_array();
        return $row['count'];
        
    }
    function get_total_after_noon_section_attendance($child_id) {
               
        $this->db->select('COUNT(*) as count');
        $this->db->where('at_child_id',$child_id);
        $this->db->where('at_trip_type','drop off');
        $this->db->where('at_pickup_or_drop_off','drop off');
        $this->db->where('at_child_status','present');
        $row=$this->db->get('Attendance')->row_array();
        return $row['count'];
        
    }
    function get_total_morning_halfday_leave($child_id) {
               
        $this->db->select('COUNT(*) as count');
        $this->db->where('at_child_id',$child_id);
        $this->db->where('at_trip_type','pickup');
        $this->db->where('at_child_status','absent');
        $row=$this->db->get('Attendance')->row_array();
        return $row['count'];
        
    }
    function get_total_after_noon_halfday_leave($child_id) {
               
        $this->db->select('COUNT(*) as count');
        $this->db->where('at_child_id',$child_id);
        $this->db->where('at_trip_type','drop off');
        $this->db->where('at_child_status','absent');
        $row=$this->db->get('Attendance')->row_array();
        return $row['count'];
        
    }
    
    function get_full_day_leave($child_id) {
        
         $this->db->select('COUNT(*) as count,date(at_time_stamp_device) as \'attdate\'');
         $this->db->where('at_child_id',$child_id);
         $this->db->group_by('attdate'); 
         $this->db->having('count(attdate) =2');
         $row=$this->db->get('Attendance')->row_array();
         if($row['count']=='')
             $row['count']=0;
         return $row['count'];
    }
    
    function get_attendance_count_by_bus_id($bus_id,$trip_id,$child_pickup_or_drop_off) {
        
        return  $this->db->query("SELECT COUNT( * ) AS  'count',  `at_trip_id` ,  `at_bus_no` 
FROM  `Attendance` 
WHERE DATE(  `at_time_stamp_device` ) = DATE( NOW( ) ) 
AND  `at_bus_no` ='$bus_id' and `at_trip_id` ='$trip_id' and `at_pickup_or_drop_off` ='$child_pickup_or_drop_off'
")->row_array();
        
    }
    
     function last_known_location_by_busn_id($bus_id,$trip_id) {
         
         $result= array();
      $result=   $this->db->query("SELECT * 
FROM  `Last_location_details` 
WHERE DATE(  `tracking_time_stamp` ) = DATE( NOW( ) ) 
AND  `tracking_bus_id` ='$bus_id' and `tracking_trip_id` ='$trip_id' order by tracking_id desc
")->result_array();
         
      if(!empty($result))   {      
         return $result[0];
      }
     else {
         return $result; 
     }
       
        
    }
    
    function get_attendance_list($trip_id,$child_trip_no_drop_off,$child_id) {
        /* $this->db->select('*');
         $this->db->where('at_trip_id',$trip_id);
         $this->db->where('at_pickup_or_drop_off',$child_trip_no_drop_off);
         $this->db->where('at_child_id',$child_id);

         return $this->db->get('Attendance')->row_array();*/
         
         
      return    $this->db->query("SELECT *
FROM  `Attendance` 
WHERE DATE(  `at_time_stamp_device` ) = DATE( NOW( ) ) 
AND  `at_child_id` ='$child_id' and `at_trip_id` ='$trip_id' and `at_pickup_or_drop_off` ='$child_trip_no_drop_off'
")->row_array();

    }
    
    
    function get_attendance_list_not_in_the_list($trip_id,$child_trip_no_drop_off,$child_ids) {    
        $sub_query='';
         if(count($child_ids)>0)
         $sub_query=" AND `at_child_id` not in (".implode(',', $child_ids).")";

      return    $this->db->query("SELECT at_child_id
FROM  `Attendance` 
WHERE DATE(  `at_time_stamp_device` ) = DATE( NOW( ) ) 
   $sub_query and `at_trip_id` ='$trip_id' and `at_pickup_or_drop_off` ='$child_trip_no_drop_off'
")->result_array();

    }
    
    
    
    
    
          //count
    
    public function count()
       {
           $this->db->from('Attendance');
          return $this->db->count_all_results();
       }
    public function is_dupplicate_entry($at_child_id,$at_trip_id,$at_bus_no,$at_trip_type,$at_pickup_or_drop_off,$at_time_stamp_device)
       {
  $result=  $this->db->query("SELECT COUNT( * ) AS  `numrows` 
FROM  `Attendance` 
WHERE  `at_child_id` =  '$at_child_id'
AND  `at_trip_id` =  '$at_trip_id'
AND  `at_bus_no` =  '$at_bus_no'
AND  `at_trip_type` =  '$at_trip_type'
AND  `at_pickup_or_drop_off` =  '$at_pickup_or_drop_off'
AND DATE( at_time_stamp_device ) = DATE( '$at_time_stamp_device' )")->row_array();
          return $result['numrows'];
       }
    
       
    function select_attendence_values_before_7($date) {
        return $this->db->query("SELECT * FROM  `Attendance` WHERE  `at_time_stamp_device` <= (  '$date' ) ")->result_array();
     }
     
         /*
     * function to add new attendance
     */
    function add_copy_attendance($params)
    {
        $this->db->insert('copy_attendance',$params);
        return $this->db->insert_id();
    }
      function delete_before_date_values($date)
    {
     return  $response = $this->db->delete('Attendance',array('at_time_stamp_device <='=>$date));
      
    } 
    
    
        function get_attendance_by_date_and_pickup_or_drop_off($bus_id,$trip_id,$child_pickup_or_drop_off,$date,$status) {
        
             $date_today=date('Y-m-d', strtotime('-7 days'));
        $datetime=$date_today.'60;60:60';
       if($date<$datetime)
       {
          return  $this->db->query("SELECT  `copy_attendance`.*,child_name,child_class,child_section
FROM  `copy_attendance` left join `Child` on `copy_attendance`.at_child_id = `Child`.child_id 
WHERE DATE(  `at_time_stamp_device` ) = '$date' 
AND  `at_bus_no` ='$bus_id' and `at_trip_id` ='$trip_id' and `at_pickup_or_drop_off` ='$child_pickup_or_drop_off' and `at_child_status` ='$status'
")->result_array();
       }
    else {
         return  $this->db->query("SELECT  `Attendance`.*,child_name,child_class,child_section
FROM  `Attendance` left join `Child` on `Attendance`.at_child_id = `Child`.child_id 
WHERE DATE(  `at_time_stamp_device` ) = '$date' 
AND  `at_bus_no` ='$bus_id' and `at_trip_id` ='$trip_id' and `at_pickup_or_drop_off` ='$child_pickup_or_drop_off' and `at_child_status` ='$status'
")->result_array();     
        }
            
       
    }
    
       function get_child_id_from_attandence($trip_id,$time_stamp)
    {
              return $this->db->query("SELECT at_child_id FROM  `Attendance` WHERE at_trip_id='$trip_id' AND `at_time_stamp_device` BETWEEN  '$time_stamp 00:00:00' AND  '$time_stamp 23:59:59' GROUP BY  `at_child_id` ASC  ")->result_array();
    }
    function get_child_id_from_attandence_with_type_c($trip_id,$time_stamp)
    {
              return $this->db->query("SELECT at_child_id FROM  `Attendance` WHERE at_trip_id='$trip_id' AND `at_time_stamp_device` BETWEEN  '$time_stamp 00:00:00' AND  '$time_stamp 23:59:59' AND at_loc_data_type like '%c' GROUP BY  `at_child_id` ASC  ")->result_array();
    }
    

    
//      function get_all_attendance_download_pickup($date)
//    {
//         $this->db->select("e.*,edu.*");
//         $this->db->from("Attendance e");
//         $this->db->join("Child edu", "edu.child_id = e.at_child_id",'left');
//         $where = "DATE(e.at_time_stamp_device) = '$date' and e.at_pickup_or_drop_off='pickup'";
//         $this->db->where($where);
//         $this->db->group_by('edu.child_id');
//         $this->db->order_by('edu.child_name', 'asc');
//         $query = $this->db->get();
//         return $query->result_array();
//    }
//    
//       function get_all_attendance_download_dropoff($date)
//    {
//         $this->db->select("e.*,edu.*");
//         $this->db->from("Attendance e");
//         $this->db->join("Child edu", "edu.child_id = e.at_child_id",'left');
//         $where = "DATE(e.at_time_stamp_device) = '$date' and e.at_child_status='present'";
//         $this->db->where($where);
//         $this->db->group_by('edu.child_id');
//         $this->db->order_by('edu.child_name', 'asc');
//         $query = $this->db->get();
//         return $query->result_array();
//    }
    
    
     function get_all_attendance_download_pickup($date)
    {
         $this->db->select("e.*,edu.*");
         $this->db->from("Attendance e");
         $this->db->join("Child edu", "edu.child_id = e.at_child_id",'left');
         $where = "DATE(e.at_time_stamp_device) = '$date' and e.at_pickup_or_drop_off='pickup'";
         $this->db->where($where);
         //$this->db->group_by('edu.child_id');
         $this->db->order_by('edu.child_name', 'asc');
         $query = $this->db->get();
         return $query->result_array();
    }
    
//       function get_all_attendance_download_dropoff($date)
//    {
//         $this->db->select("e.*,edu.*");
//         $this->db->from("Attendance e");
//         $this->db->join("Child edu", "edu.child_id = e.at_child_id",'left');
//         $where = "DATE(e.at_time_stamp_device) = '$date' and e.at_child_status='present'";
//         $this->db->where($where);
//         $this->db->group_by('edu.child_id');
//         $this->db->order_by('edu.child_name', 'asc');
//         $query = $this->db->get(); 
//         return $query->result_array(); 
//    }
    
    
        function get_all_attendance_download_dropoff($date)
    {
         $this->db->select("e.*,edu.*");
         $this->db->from("Attendance e");
         $this->db->join("Child edu", "edu.child_id = e.at_child_id",'left');
         $where = "DATE(e.at_time_stamp_device) = '$date' and e.at_pickup_or_drop_off='drop off'";
         $this->db->where($where);
        // $this->db->group_by('edu.child_id');
         $this->db->order_by('edu.child_name', 'asc');
         $query = $this->db->get();
         return $query->result_array();
    }
    
    
    //before 7 days
       function get_all_copy_attendance_download_pickup($date)
    {
         $this->db->select("e.*,edu.*");
         $this->db->from("copy_attendance e");
         $this->db->join("Child edu", "edu.child_id = e.at_child_id",'left');
         $where = "DATE(e.at_time_stamp_device) = '$date' and e.at_pickup_or_drop_off='pickup'";
         $this->db->where($where);
         //$this->db->group_by('edu.child_id');
         $this->db->order_by('edu.child_name', 'asc');
         $query = $this->db->get();
         return $query->result_array();
    }
     
        function get_all_copy_attendance_download_dropoff($date)
    {
         $this->db->select("e.*,edu.*");
         $this->db->from("copy_attendance e");
         $this->db->join("Child edu", "edu.child_id = e.at_child_id",'left');
         $where = "DATE(e.at_time_stamp_device) = '$date' and e.at_pickup_or_drop_off='drop off'";
         $this->db->where($where);
        // $this->db->group_by('edu.child_id');
         $this->db->order_by('edu.child_name', 'asc');
         $query = $this->db->get();
         return $query->result_array();
    }
    
         function copy_and_save_values_before_7()
    {
         $sql="insert into copy_attendance  SELECT * FROM `Attendance` WHERE date(`at_time_stamp`) < date(DATE_SUB(date(now()),INTERVAL 7 DAY))";
         return $this->db->query($sql);
    }
     function delete_values_before_7()
    {
         $sql="DELETE FROM `Attendance` WHERE date(`at_time_stamp`) < date(DATE_SUB(date(now()),INTERVAL 7 DAY))";
         return $this->db->query($sql);
    }
    
    
       function get_all_attendance_download($date)
    {
         $this->db->select("e.*,edu.*");
         $this->db->from("Attendance e");
         $this->db->join("Child edu", "edu.child_id = e.at_child_id",'left');
         $where = "DATE(e.at_time_stamp_device) = '$date' and substr(e.at_loc_data_type, -1)='c' and e.at_pickup_or_drop_off='pickup'";
         $this->db->where($where);
         //$this->db->group_by('edu.child_id');
         $this->db->order_by('edu.child_name', 'asc');
         $query = $this->db->get();
         return $query->result_array();
    }
      function get_all_copy_attendance_download($date)
    {
         $this->db->select("e.*,edu.*");
         $this->db->from("copy_attendance e");
         $this->db->join("Child edu", "edu.child_id = e.at_child_id",'left');
         $where = "DATE(e.at_time_stamp_device) = '$date' and substr(e.at_loc_data_type, -1)='c' and e.at_pickup_or_drop_off='pickup'";
         $this->db->where($where);
         //$this->db->group_by('edu.child_id');
         $this->db->order_by('edu.child_name', 'asc');
         $query = $this->db->get();
         return $query->result_array();
    }
    
         function get_count_trips_in_attendance_download($from,$to)
    {
   $result= $this->db->query("SELECT * FROM (SELECT count(*) AS 'count',`at_child_id` FROM (SELECT * FROM `Attendance` WHERE date(`at_time_stamp_device`) BETWEEN date('$from') AND date('$to') "
                     . "AND  `at_child_status`='present' AND `at_pickup_or_drop_off`='pickup' UNION SELECT * FROM `copy_attendance` WHERE date(`at_time_stamp_device`) BETWEEN date('$from') AND date('$to') "
                     . "AND  `at_child_status`='present' AND `at_pickup_or_drop_off`='pickup')  as sub   GROUP BY `at_child_id`) as main  LEFT JOIN Child on main.`at_child_id` =Child.child_id LEFT JOIN Bus on Bus.bus_id=Child.child_bus_no_pickup")->result_array();
          //   echo $this->db->last_query($result);exit();
             return $result;
          
    }
    
    
    
        function get_all_attendance_download_pickup_lsedit($date)
    {
          $result= $this->db->query("SELECT `e`.*, `edu`.* FROM `Attendance` `e` LEFT JOIN `Child` `edu` ON `edu`.`child_id` = `e`.`at_child_id` WHERE DATE(e.at_time_stamp_device) = '$date' "
           . "and `e`.`at_pickup_or_drop_off` = 'pickup' UNION ALL SELECT `c`.*, `d`.* FROM `copy_attendance` `c` LEFT JOIN `Child` `d`ON `d`.`child_id` = `c`.`at_child_id` "
           . "WHERE DATE(c.at_time_stamp_device) = '$date' and `c`.`at_pickup_or_drop_off` = 'pickup'")->result_array();
          //   echo $this->db->last_query($result);exit();
             return $result;
    }
      
    
     
        function get_all_attendance_download_dropoff_lsedit($date)
    {
          $result= $this->db->query("SELECT `e`.*, `edu`.* FROM `Attendance` `e` LEFT JOIN `Child` `edu` ON `edu`.`child_id` = `e`.`at_child_id` WHERE DATE(e.at_time_stamp_device) = '$date' "
           . "and `e`.`at_pickup_or_drop_off` = 'drop off' UNION ALL SELECT `c`.*, `d`.* FROM `copy_attendance` `c` LEFT JOIN `Child` `d`ON `d`.`child_id` = `c`.`at_child_id` "
           . "WHERE DATE(c.at_time_stamp_device) = '$date' and `c`.`at_pickup_or_drop_off` = 'drop off'")->result_array();
          //   echo $this->db->last_query($result);exit();
             return $result;
    }
    
 
    
}
