<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Bu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bu by bus_id
     */
    function get_bu($bus_id)
    {
        return $this->db->get_where('Bus',array('bus_id'=>$bus_id))->row_array();
    }
    
       
       function get_bus_name($bus_name)
    {
        return $this->db->get_where('Bus',array('bus_name'=>$bus_name))->row_array();
    }
    /*
     * Get all bus
     */
    function get_all_bus()
    {
        return $this->db->get('Bus')->result_array();
    }
    
    //count
     function count() 
    {
        $this->db->from('Bus');
        return $this->db->count_all_results();
    }
    /*
     * function to add new bu
     */
    function add_bu($params)
    {
        $this->db->insert('Bus',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bu
     */
    function update_bu($bus_id,$params)
    {
        $this->db->where('bus_id',$bus_id);
        $response = $this->db->update('Bus',$params);
        if($response)
        {
            return "bu updated successfully";
        }
        else
        {
            return "Error occuring while updating bu";
        }
    }
    
    /*
     * function to delete bu
     */
    function delete_bu($bus_id)
    {
        $response = $this->db->delete('Bus',array('bus_id'=>$bus_id));
        if($response)
        {
            return "bu deleted successfully";
        }
        else
        {
            return "Error occuring while deleting bus";
        }
    }
    
      /*
     * function to status bus
     */
    function status_bus($bus_id,$status)
    {  
        $this->db->set('bus_status', $status, FALSE);
       $this->db->where('bus_id',$bus_id);
       $response = $this->db->update('Bus');
        if($response)
        {
            return "Bus Status updated successfully";
        }
        else
        {
            return "Error occuring while updating Bus Status";
        }
    }
    
    
    
       function get_bus_pickup($pick)
    {
       $this->db->join('Bus', 'Bus.bus_id = Trip.trip_bus_id');
       $this->db->group_by('Bus.bus_id'); 
        return $this->db->get_where('Trip',array('trip_type'=>$pick))->result_array();
    }   
       function get_bus_dropoff($drop)
    {
        $this->db->join('Bus', 'Bus.bus_id = Trip.trip_bus_id');
         $this->db->group_by('Bus.bus_id');
        return $this->db->get_where('Trip',array('trip_type'=>$drop))->result_array();
    } 
    /*
     * Get bus_id by bus_name
     */
    function get_bus_id($bus_name)
    {
        return $this->db->get_where('Bus',array('bus_name'=>$bus_name))->row_array();
    }
    /*
     * Get bus_id by bus_desc
     */
    function get_bus_id_by_desc($bus_desc)
    {
        return $this->db->get_where('Bus',array('bus_desc'=>$bus_desc))->row_array();
    }
    
    /*
     * Get bus_id by running status
     */
    function get_bus_by_running_status($running_satus)
    {
        return $this->db->get_where('Bus',array('bus_running_satus'=>$running_satus))->result_array();
    }
    
         function truncate_bus() {
        $response = $this->db->truncate('Bus');
        if ($response) {
            return "Bus deleted successfully";
        } else {
            return "Error occuring while deleting Bus";
        }
    }
    
      function get_running_buses()
    {
        return $this->db->get_where('Bus',array('bus_running_satus'=>'running'))->result_array();
    }
  
      /*
     * function to update update_bus_running_satus
     */
    function update_bus_running_satus($bus_id)
    {
        $data=array('bus_running_satus'=>'not running');
        $this->db->where('bus_id',$bus_id);
        $this->db->update('Bus',$data);
       
    }
}
