<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Bus_app_user_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bus_app_user by bus_app_user_id
     */
    function get_bus_app_user($bus_app_user_id)
    {
        return $this->db->get_where('Bus_App_User',array('bus_app_user_id'=>$bus_app_user_id))->row_array();
    }
    
    /*
     * Get all bus_app_user
     */
    function get_all_bus_app_user()
    {
        $this->db->select('*');
        $this->db->from('Bus_App_User');
        $this->db->join('Bus', 'Bus.bus_id = Bus_App_User.bus_app_user_bus_id');
        $query = $this->db->get();
      return $query->result_array() ;
    }
    
    /*
     * function to add new bus_app_user
     */
    function add_bus_app_user($params)
    {
        $this->db->insert('Bus_App_User',$params);
        return $this->db->insert_id();
    }
    
    /* 
     * function to update bus_app_user
     */
    function update_bus_app_user($bus_app_user_id,$params)
    {
        $this->db->where('bus_app_user_id',$bus_app_user_id);
        $response = $this->db->update('Bus_App_User',$params);
        if($response)
        {
            return "bus_app_user updated successfully";
        }
        else
        {
            return "Error occuring while updating bus_app_user";
        }
    }
    function update_bus_app_user_by_bus_id($bus_app_bus_id,$params)
    {
        $this->db->where('bus_app_user_bus_id',$bus_app_bus_id);
        $response = $this->db->update('Bus_App_User',$params);
        if($response)
        {
            return "bus_app_user updated successfully";
        }
        else
        {
            return "Error occuring while updating bus_app_user";
        }
    }
    
    /*
     * function to delete bus_app_user
     */
    function delete_bus_app_user($bus_app_user_id)
    {
        $response = $this->db->delete('Bus_App_User',array('bus_app_user_id'=>$bus_app_user_id));
        if($response)
        {
            return "bus_app_user deleted successfully";
        }
        else
        {
            return "Error occuring while deleting bus_app_user";
        }
    }
        /*
     * Get bus_app_user by bus_app_user_name and bus_app_user_password 
     */
    function get_bus_app_user_by_username_pass($bus_app_user_name,$bus_app_user_password)
    {
        return $this->db->get_where('Bus_App_User',array('bus_app_user_name'=>$bus_app_user_name,'bus_app_user_password'=>$bus_app_user_password))->row_array();
    }
    
      /*
     * function to status child
     */
    function status_bus_app_user($bus_app_user_id,$status)
    {  
        $this->db->set('bus_user_status', $status, FALSE);
       $this->db->where('bus_app_user_id',$bus_app_user_id);
       $response = $this->db->update('Bus_App_User');
        if($response)
        {
            return "User Status updated successfully";
        }
        else
        {
            return "Error occuring while updating User Status";
        }
    }
    
    
 public function auth($data) {
           $user_name=$data['Username'];
           $password=$data['Password'];
           
           $result= $this->db->get_where('User',array('user_id'=>$user_name,'user_password'=>$password))->row_array();
            
            
        //   if(strtolower($user_name)=='admin' && strtolower($password)=='admin'){
           
           if(!empty($result)){
              $this->session->set_userdata('user', $result);
               return TRUE;
           }  else {
               return FALSE; 
           }
        }
        public function auth_session() {
           if($this->session->has_userdata('user'))
           {
             return TRUE;
           }  else {
               return FALSE; 
           }
        }
        
        public function logout() {
            $this->session->unset_userdata('user');
        }
    function truncate_bus_app_users() {
        $response = $this->db->truncate('Bus_App_User');
        if ($response) {
            return "Bus App users deleted successfully";
        } else {
            return "Error occuring while deleting Bus App users";
        }
    }
    
     function get_bus_app_user_by_bus_id($bus_app_bus_id)
    {
         return $this->db->get_where('Bus_App_User',array('bus_app_user_bus_id'=>$bus_app_bus_id))->row_array();
    }
}
