<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Child_live_buss_update_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get attendance by at_id
     */
    function get_child_live_buss_update($child_id)
    {
        
        $where = "date(`live_update_time`) =date(now())";
        $this->db->where($where);
        return $this->db->get_where('child_live_buss_update',array('live_child_id'=>$child_id))->row_array();
    }
    
 
    /*
     * function to add new 
     */
    function replace_status($params)
    {
        $this->db->replace('child_live_buss_update',$params);
        return null;
    }
    
   
 
    
}
