<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Custom_notification_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get notification by custom_no_id
     */
    function get_notification($custom_no_id)
    {
        
        return $this->db->get_where('custom_notification',array('custom_no_id'=>$custom_no_id))->row_array();
    }
    
    /*
     * Get all notification
     */
    function get_all_notification()
    {
        return $this->db->get('custom_notification')->result_array();
    }
    
    /*
     * function to add new notification
     */
    function add_notification($params)
    {
        $this->db->insert('custom_notification',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update notification
     */
    function update_notification($custom_no_id,$params)
    {
        $this->db->where('custom_no_id',$custom_no_id);
        $response = $this->db->update('custom_notification',$params);
        if($response)
        {
            return "notification updated successfully";
        }
        else
        {
            return "Error occuring while updating notification";
        }
    }
    
    /*
     * function to delete notification
     */
    function delete_notification($custom_no_id)
    {
        $response = $this->db->delete('custom_notification',array('custom_no_id'=>$custom_no_id));
        if($response)
        {
            return "notification deleted successfully";
        }
        else
        {
            return "Error occuring while deleting notification";
        }
    }
  
    
    
    
}
