<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Device_app_user_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get device_app_user by device_app_user_id
     */
    function get_device_app_user($device_app_user_id)
    {
        return $this->db->get_where('Device_App_User',array('device_app_user_id'=>$device_app_user_id))->row_array();
    }
    
    /*
     * Get all device_app_user count
     */
    function get_all_device_app_user_count()
    {
        $this->db->from('Device_App_User');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all device_app_user
     */
    function get_all_device_app_user($limit = null, $offset = NULL)
    {
        $this->db->order_by('device_app_user_id', 'desc');
        $this->db->limit($limit, $offset);
        return $this->db->get('Device_App_User')->result_array();
    }
        
    /*
     * function to add new device_app_user
     */
    function add_device_app_user($params)
    {
        $this->db->insert('Device_App_User',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update device_app_user
     */
    function update_device_app_user($device_app_user_id,$params)
    {
        $this->db->where('device_app_user_id',$device_app_user_id);
        return $this->db->update('Device_App_User',$params);
    }
    
    /*
     * function to delete device_app_user
     */
    function delete_device_app_user($device_app_user_id)
    {
        return $this->db->delete('Device_App_User',array('device_app_user_id'=>$device_app_user_id));
    }
    
    
     
      /*
     * function to status child
     */
    function status_device_app_user($user_id,$status)
    {  
        $this->db->set('device_user_status', $status, FALSE);
       $this->db->where('device_app_user_id',$user_id);
       $response = $this->db->update('Device_App_User');
        if($response)
        {
            return "User Status updated successfully";
        }
        else
        {
            return "Error occuring while updating User Status";
        }
    }
    
     function get_device_app_user_by_username_pass($bus_app_user_name,$bus_app_user_password)
    {
        return $this->db->get_where('Device_App_User',array('device_app_user_name'=>$bus_app_user_name,'device_app_user_password'=>$bus_app_user_password))->row_array();
    }
    
    
   
}
