<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Finish_trip_detail_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get finish_trip_detail by finish_id
     */
    function get_finish_trip_detail($finish_id)
    {
        return $this->db->get_where('Finish_trip_details',array('finish_id'=>$finish_id))->row_array();
    }
    
    /*
     * Get all Finish_trip_details
     */
    function get_all_Finish_trip_details()
    {
        return $this->db->get('Finish_trip_details')->result_array();
    }
    
    /*
     * function to add new finish_trip_detail
     */
    function add_finish_trip_detail($params)
    {
        $this->db->insert('Finish_trip_details',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update finish_trip_detail
     */
    function update_finish_trip_detail($finish_id,$params)
    {
        $this->db->where('finish_id',$finish_id);
        $response = $this->db->update('Finish_trip_details',$params);
        if($response)
        {
            return "finish_trip_detail updated successfully";
        }
        else
        {
            return "Error occuring while updating finish_trip_detail";
        }
    }
    
    /*
     * function to delete finish_trip_detail
     */
    function delete_finish_trip_detail($finish_id)
    {
        $response = $this->db->delete('Finish_trip_details',array('finish_id'=>$finish_id));
        if($response)
        {
            return "finish_trip_detail deleted successfully";
        }
        else
        {
            return "Error occuring while deleting finish_trip_detail";
        }
    }
        /*
     * Get finish_trip_detail by bustrip
     */
    function get_finish_trip_detail_by_bustrip($trip_id,$bus_id,$date)
    {
        return $this->db->get_where('Finish_trip_details',array('finish_trip_id'=>$trip_id,'finish_bus_id'=>$bus_id,'date(finish_time_stamp)'=>$date))->row_array();
    }
    
}
