<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Localization_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get localization by localization_id
     */
    function get_localization($localization_id)
    {
        return $this->db->get_where('localization',array('localization_id'=>$localization_id))->row_array();
    }
        
    /*
     * Get all localization
     */
    function get_all_localization()
    {
        $this->db->order_by('localization_id', 'asc');
        return $this->db->get('localization')->result_array();
    }
        
    /*
     * function to add new localization
     */
    function add_localization($params)
    {
        $this->db->insert('localization',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update localization
     */
    function update_localization($localization_id,$params)
    {
        $this->db->where('localization_id',$localization_id);
        return $this->db->update('localization',$params);
    }
    
    /*
     * function to delete localization
     */
    function delete_localization($localization_id)
    {
        return $this->db->delete('localization',array('localization_id'=>$localization_id));
    }
}
