<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Logo_image_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get logo_image by logo_id
     */
    function get_logo_image($logo_id)
    {
        return $this->db->get_where('Logo_images',array('logo_id'=>$logo_id))->row_array();
    }
    
    /*
     * Get all logo_images
     */
    function get_all_logo_images()
    {
        return $this->db->get('Logo_images')->result_array();
    }
    
    /*
     * function to add new logo_image
     */
    function add_logo_image($params)
    {
        $this->db->insert('Logo_images',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update logo_image
     */
    function update_logo_image($logo_id,$params)
    {
        $this->db->where('logo_id',$logo_id);
        $response = $this->db->update('Logo_images',$params);
        if($response)
        {
            return "logo_image updated successfully";
        }
        else
        {
            return "Error occuring while updating logo_image";
        }
    }
    
    /*
     * function to delete logo_image
     */
    function delete_logo_image($logo_id)
    {
        $response = $this->db->delete('Logo_images',array('logo_id'=>$logo_id));
        if($response)
        {
            return "logo_image deleted successfully";
        }
        else
        {
            return "Error occuring while deleting logo_image";
        }
    }
}
