<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Lsedit_app_user_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lsedit_app_user by lsedit_app_user_id
     */
    function get_lsedit_app_user($lsedit_app_user_id)
    {
        return $this->db->get_where('Lsedit_App_User',array('lsedit_app_user_id'=>$lsedit_app_user_id))->row_array();
    }
    
    /*
     * Get all lsedit_app_user
     */
    function get_all_lsedit_app_user()
    {
        $this->db->order_by("lsedit_app_user_id", "asc");
        return $this->db->get('Lsedit_App_User')->result_array();
    }
    
    /*
     * function to add new lsedit_app_user
     */
    function add_lsedit_app_user($params)
    {
        $this->db->insert('Lsedit_App_User',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lsedit_app_user
     */
    function update_lsedit_app_user($lsedit_app_user_id,$params)
    {
        $this->db->where('lsedit_app_user_id',$lsedit_app_user_id);
        $response = $this->db->update('Lsedit_App_User',$params);
        if($response)
        {
            return "lsedit_app_user updated successfully";
        }
        else
        {
            return "Error occuring while updating lsedit_app_user";
        }
    }
    
    /*
     * function to delete lsedit_app_user
     */
    function delete_lsedit_app_user($lsedit_app_user_id)
    {
        $response = $this->db->delete('Lsedit_App_User',array('lsedit_app_user_id'=>$lsedit_app_user_id));
        if($response)
        {
            return "lsedit_app_user deleted successfully";
        }
        else
        {
            return "Error occuring while deleting lsedit_app_user";
        }
    }
    
        /*
     * Get parent_app_user by parent_app_user_name and parent_app_user_password 
     */
    function get_lsedit_app_user_by_username_pass($lsedit_app_user_name,$lsedit_app_user_password)
    {
        return $this->db->get_where('Lsedit_App_User',array('lsedit_user_name'=>$lsedit_app_user_name,'lsedit_user_password'=>$lsedit_app_user_password))->row_array();
    }
}
