<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Notification_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get notification by n_id
     */
    function get_notification($n_id)
    {
        
        return $this->db->get_where('Notification',array('n_id'=>$n_id))->row_array();
    }
    
    /*
     * Get all notification
     */
    function get_all_notification()
    {
        return $this->db->get('Notification')->result_array();
    }
    
    /*
     * function to add new notification
     */
    function add_notification($params)
    {
        $this->db->insert('Notification',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update notification
     */
    function update_notification($n_id,$params)
    {
        $this->db->where('n_id',$n_id);
        $response = $this->db->update('Notification',$params);
        if($response)
        {
            return "notification updated successfully";
        }
        else
        {
            return "Error occuring while updating notification";
        }
    }
    
    /*
     * function to delete notification
     */
    function delete_notification($n_id)
    {
        $response = $this->db->delete('Notification',array('n_id'=>$n_id));
        if($response)
        {
            return "notification deleted successfully";
        }
        else
        {
            return "Error occuring while deleting notification";
        }
    }
    
    /* get notification by child id */
    
    function get_notification_by_child_id($child_id) {
       $this->db->where('n_child_id',$child_id);
       $this->db->order_by("n_id", "desc"); 
       return  $this->db->get('Notification')->result_array();
        
    }
    
    /* get notification by child id */
    
    function get_notification_by_child_id_and_date($child_id,$date) {
       $time_stamp1= date('Y-m-d', strtotime($date));
       $this->db->where('n_child_id',$child_id);
       $where = "n_time_stamp BETWEEN  '$time_stamp1 00:00:00' AND  '$time_stamp1 23:59:59'";
       $this->db->where($where)    ;
       $this->db->order_by('n_id','desc');
       return  $this->db->get('Notification')->result_array();
        
    }
    
    
            function get_last_notification_by_child_id($child_id) {

           return $this->db->query("SELECT n_id, `n_title` ,`n_msg`,`n_time_stamp`,`n_send_type`,`n_type`,`n_child_id`,`n_status`,`n_trip_type`FROM  `Notification` WHERE  `n_child_id` =  '$child_id' ORDER BY  `n_id` DESC limit 1")->result_array();
    } 
    
    
    
}
