<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Parent_child_mapping_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get parent_child_mapping by mapping_id
     */
    function get_parent_child_mapping($mapping_id)
    {
        return $this->db->get_where('Parent_child_mapping',array('mapping_id'=>$mapping_id))->row_array();
    }
    
    /*
     * Get all parent_child_mapping
     */
    function get_all_parent_child_mapping()
    {
        return $this->db->get('Parent_child_mapping')->result_array();
    }
    
    /*
     * function to add new parent_child_mapping
     */
    function add_parent_child_mapping($params)
    {
        $this->db->insert('Parent_child_mapping',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update parent_child_mapping
     */
    function update_parent_child_mapping($mapping_id,$params)
    {
        $this->db->where('mapping_id',$mapping_id);
        $response = $this->db->update('Parent_child_mapping',$params);
        if($response)
        {
            return "parent_child_mapping updated successfully";
        }
        else
        {
            return "Error occuring while updating parent_child_mapping";
        }
    }
    
    /*
     * function to delete parent_child_mapping
     */
    function delete_parent_child_mapping($mapping_id)
    {
        $response = $this->db->delete('Parent_child_mapping',array('mapping_id'=>$mapping_id));
        if($response)
        {
            return "parent_child_mapping deleted successfully";
        }
        else
        {
            return "Error occuring while deleting parent_child_mapping";
        }
    }
       function truncate_Parent_child_mapping() {
        $response = $this->db->truncate('Parent_child_mapping');
        if ($response) {
            return "Parent child mapping deleted successfully";
        } else {
            return "Error occuring while deleting Parent child mapping";
        }
    }
}
