<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Push_msg_map_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get push_msg_map by push_msg_id
     */
    function get_push_msg_map($push_msg_id)
    {
        return $this->db->get_where('Push_msg_map',array('push_msg_id'=>$push_msg_id))->row_array();
    }
    
    /*
     * Get all push_msg_map
     */
    function get_all_push_msg_map()
    {
        return $this->db->get('Push_msg_map')->result_array();
    }
    
    /*
     * function to add new push_msg_map
     */
    function add_push_msg_map($params)
    {
        $this->db->insert('Push_msg_map',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update push_msg_map
     */
    function update_push_msg_map($push_msg_id,$params)
    {
        $this->db->where('push_msg_id',$push_msg_id);
        $response = $this->db->update('Push_msg_map',$params);
        if($response)
        {
            return "push_msg_map updated successfully";
        }
        else
        {
            return "Error occuring while updating push_msg_map";
        }
    }
    
    /*
     * function to delete push_msg_map
     */
    function delete_push_msg_map($push_msg_id)
    {
        $response = $this->db->delete('Push_msg_map',array('push_msg_id'=>$push_msg_id));
        if($response)
        {
            return "push_msg_map deleted successfully";
        }
        else
        {
            return "Error occuring while deleting push_msg_map";
        }
    }
    /*
     * function to delete push_msg_map
     */
    function delete_push_msg_map_batch($push_msg_id)
    {
       
        $this->db->where_in('push_msg_id', $push_msg_id);
        $this->db->delete('Push_msg_map'); 
        
        return TRUE;
    }
   
     /*
     * Get all push_msg_map
     */
    function get_all_push_msg_map_child_id($child_id)
    {
        return $this->db->query("select DISTINCT push_msg_device_token,push_language_name from Push_msg_map where push_msg_child_id='$child_id'")->result_array();
        
    }
     /*
     * Get all push_msg_map
     */
    function get_all_push_msg_map_multiple_child_id($trip_id)
    {
        return $this->db->query("SELECT DISTINCT push_msg_device_token,push_msg_child_id,push_language_name FROM Push_msg_map WHERE push_msg_child_id IN (SELECT `child_id` FROM Child WHERE `child_trip_no_pickup` ='$trip_id' OR `child_trip_no_drop_off` ='$trip_id')")->result_array();
    }
    
     function get_all_push_msg_map_multiple_child_id_bus_id($bus_id)
    {
        return $this->db->query("SELECT DISTINCT push_msg_device_token,push_msg_child_id,push_language_name FROM Push_msg_map WHERE push_msg_child_id IN (SELECT `child_id` FROM Child WHERE `child_bus_no_pickup` ='$bus_id' OR `child_bus_no_drop_off` ='$bus_id')")->result_array();
    }
}
