<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Setting_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get setting by set_id
     */
    function get_setting($set_id)
    {
        return $this->db->get_where('Settings',array('set_id'=>$set_id))->row_array();
    }
    
    /*
     * Get all settings
     */
    function get_all_settings()
    {
        
        return $this->db->get('Settings')->result_array();
    }
    function get_current_settings()
    {
        
        return $this->db->get('Settings')->row_array();
    }

    
    /*
     * function to add new setting
     */
    function add_setting($params)
    {
        $this->db->insert('Settings',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update setting
     */
    function update_setting($set_id,$params)
    {
       // $this->db->where('set_id',$set_id);
        $response = $this->db->update('Settings',$params);
    }
    
    /*
     * function to delete setting
     */
    function delete_setting($set_id)
    {
        $response = $this->db->delete('Settings',array('set_id'=>$set_id));
        if($response)
        {
            return "setting deleted successfully";
        }
        else
        {
            return "Error occuring while deleting setting";
        }
    }
    
          /*
     * function to status child
     */
    function status_setting_model($set_id,$status)
    {  
        $this->db->set('set_status', $status, FALSE);
       $this->db->where('set_id',$set_id);
       $response = $this->db->update('Settings');
        if($response)
        {
            return "Settings Status updated successfully";
        }
        else
        {
            return "Error occuring while updating Settings Status";
        }
    }
      function get_lati_longi()
    {
       return $this->db->query("SELECT school_latitude,school_longitude FROM `Settings`")->row_array();
    }
      function get_supervisor_details()
    {
       return $this->db->query("SELECT supervisor_name,supervisor_phone FROM `Settings`")->row_array();
    }
    
}
