<?php

/*
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */

class Summery_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /*
     * function to add new attendance
     */

   

    function get_count_bus_running_notrunning() {

         $result=  $this->db->query("SELECT COUNT(u1.`bus_id`) AS count , 'count_running' as type "
                . "FROM Bus u1 WHERE u1.`bus_running_satus` LIKE 'running' UNION ALL SELECT COUNT(u2.`bus_id`) AS count , 'count_notrunning' FROM Bus u2 WHERE u2.`bus_running_satus` LIKE 'not running'")->result_array();
          return $result;
          
      }

   function get_count_bus_pickup_dropoff() {

         $result=  $this->db->query("SELECT COUNT(u1.`bus_id`) AS count , 'count_pickup' as type "
                 . "FROM Bus u1 WHERE u1.`bus_child_pickup_or_drop_off` LIKE 'pickup' UNION ALL SELECT COUNT(u2.`bus_id`) AS count , 'count_dropoff' FROM Bus u2 WHERE u2.`bus_child_pickup_or_drop_off` LIKE 'drop off'")->result_array();
          return $result;
          
      }   
      
        function get_count_child_trip_pickup_dropoff() {

         $result=  $this->db->query("SELECT COUNT(u1.`child_id`) AS count , 'count_pickup' as type FROM Child u1
        WHERE u1.`child_trip_no_pickup`!=0 and u1.`child_trip_no_pickup`!='' UNION ALL SELECT COUNT(u2.`child_id`) AS count , 'count_dropoff' FROM Child u2 WHERE u2.`child_trip_no_drop_off`!=0 and u2.`child_trip_no_drop_off`!=''")->result_array();
          return $result;
          
      } 
}

