<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Supervisor_app_user_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get supervisor_app_user by supervisor_app_user_id
     */
    function get_supervisor_app_user($supervisor_app_user_id)
    {
        return $this->db->get_where('Supervisor_App_User',array('supervisor_app_user_id'=>$supervisor_app_user_id))->row_array();
    }
    
    /*
     * Get all supervisor_app_user
     */
    function get_all_supervisor_app_user()
    {
        $this->db->order_by("supervisor_app_user_id", "asc");
        return $this->db->get('Supervisor_App_User')->result_array();
    }
    
    /*
     * function to add new supervisor_app_user
     */
    function add_supervisor_app_user($params)
    {
        $this->db->insert('Supervisor_App_User',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update supervisor_app_user
     */
    function update_supervisor_app_user($supervisor_app_user_id,$params)
    {
        $this->db->where('supervisor_app_user_id',$supervisor_app_user_id);
        $response = $this->db->update('Supervisor_App_User',$params);
        if($response)
        {
            return "supervisor_app_user updated successfully";
        }
        else
        {
            return "Error occuring while updating supervisor_app_user";
        }
    }
    
    /*
     * function to delete supervisor_app_user
     */
    function delete_supervisor_app_user($supervisor_app_user_id)
    {
        $response = $this->db->delete('Supervisor_App_User',array('supervisor_app_user_id'=>$supervisor_app_user_id));
        if($response)
        {
            return "supervisor_app_user deleted successfully";
        }
        else
        {
            return "Error occuring while deleting supervisor_app_user";
        }
    }
    
        /*
     * Get parent_app_user by parent_app_user_name and parent_app_user_password 
     */
    function get_supervisor_app_user_by_username_pass($supervisor_app_user_name,$supervisor_app_user_password)
    {
        return $this->db->get_where('Supervisor_App_User',array('supervisor_user_name'=>$supervisor_app_user_name,'supervisor_user_password'=>$supervisor_app_user_password))->row_array();
    }
}
