<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Trip_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get trip by trip_id
     */
    function get_trip($trip_id)
    {
        return $this->db->get_where('Trip',array('trip_id'=>$trip_id))->row_array();
    }
    
    /*
     * Get all trip
     */
    function get_all_trip()
    {
        $this->db->join('Bus', 'Bus.bus_id = Trip.trip_bus_id');
        return $this->db->get('Trip')->result_array();
        
    }
    
        /*
     * Get all trip
     */
    function get_full_trip()
    {
        return $this->db->get('Trip')->result_array();
        
    }
    
    
    /*
     * function to add new trip
     */
    function add_trip($params)
    {
        $this->db->insert('Trip',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update trip
     */
    function update_trip($trip_id,$params)
    {
        $this->db->where('trip_id',$trip_id);
        $response = $this->db->update('Trip',$params);
        if($response)
        {
            return "trip updated successfully";
        }
        else
        {
            return "Error occuring while updating trip";
        }
    }
    
    /*
     * function to delete trip
     */
    function delete_trip($trip_id)
    {
        $response = $this->db->delete('Trip',array('trip_id'=>$trip_id));
        if($response)
        {
            return "trip deleted successfully";
        }
        else
        {
            return "Error occuring while deleting trip";
        }
    }
        /*
     * Get all trip by bus_id
     */
    function get_all_trip_by_bus_id($trip_bus_id)
    {
         return $this->db->get_where('Trip',array('trip_bus_id'=>$trip_bus_id))->result_array();
    }
        /*
     * Get all active  trip by bus_id
     */
    function get_all_active_trip_by_bus_id($trip_bus_id,$trip_time='all')
    {
         $sub_qry="";
        if($trip_time!='all'){
            $sub_qry=' and time like "%{'.$trip_time.'}%"';
        }
         return $this->db->query("SELECT * FROM `Trip` where `trip_bus_id`='$trip_bus_id' and `trip_id` not in (select finish_trip_id as 'trip_id' from  Finish_trip_details WHERE DATE(  `finish_time_stamp` ) = DATE( NOW( ) ) ) and trip_status='0' $sub_qry")->result_array();
    }
    
         /*
     * function to status trip
     */
    function status_trip($trip_id,$status)
    {  
        $this->db->set('trip_status', $status, FALSE);
       $this->db->where('trip_id',$trip_id);
       $response = $this->db->update('Trip');
        if($response)
        {
            return "Trip Status updated successfully";
        }
        else
        {
            return "Error occuring while updating Trip Status";
        }
    }
     /*
     * Get all bus
     */
//    function get_all_bus()
//    {
//         return $this->db->get('Bus')->result_array();
//    }

    
   function get_trip_with_bus_id_index($bus_id)
    {
          
    return $this->db->get_where('Trip',array('trip_bus_id'=>$bus_id))->result_array();
    }
    
      function get_trip_with_bus_id($bus_id)
    {
          
     $this->db->select('*');
    $this->db->from('Bus');
    $this->db->join('Trip', 'Trip.trip_bus_id = Bus.bus_id');
    $where = "Bus.bus_running_satus='running'";
    $this->db->where($where)    ;
    $where = "Bus.bus_id='$bus_id'";
    $this->db->where($where)    ;
    $this->db->group_by('bus_id');
    return $this->db->get()->row_array();
    }
    
    
      /*
     * Get trip by trip_id
     */
    function get_trip_id($trip_name)
    {
        return $this->db->get_where('Trip',array('trip_no'=>$trip_name))->row_array();
    }
    
    
     function truncate_trip() {
        $response = $this->db->truncate('Trip');
        if ($response) {
            return "Trip deleted successfully";
        } else {
            return "Error occuring while deleting Trip";
        }
    }
    
    
    
        /*
     * function to add new Finish_trip_details

     */
    function insert_finish_trip_details($params)
    {
        $this->db->insert('Finish_trip_details',$params);
        return $this->db->insert_id();
    }
}
