<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user by id
     */
    function get_user($id)
    {
        return $this->db->get_where('User',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all user
     */
    function get_all_user()
    {
        return $this->db->get_where('User',array('user_type != '=>'0'))->result_array();
    }
    
    /*
     * function to add new user
     */
    function add_user($params)
    {
        $this->db->insert('User',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user
     */
    function update_user($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('User',$params);
        if($response)
        {
            return "user updated successfully";
        }
        else
        {
            return "Error occuring while updating user";
        }
    }
    
    /*
     * function to delete user
     */
    function delete_user($id)
    {
        $response = $this->db->delete('User',array('id'=>$id));
        if($response)
        {
            return "user deleted successfully";
        }
        else
        {
            return "Error occuring while deleting user";
        }
        
    }
    public function auth($data) {
           $user_name=$data['Username'];
           $password=$data['Password'];
           
           $result= $this->db->get_where('User',array('user_id'=>$user_name,'user_password'=>$password))->row_array();
            
            
        //   if(strtolower($user_name)=='admin' && strtolower($password)=='admin'){
           
           if(!empty($result)){
              $this->session->set_userdata('user', $result);
               return TRUE;
           }  else {
               return FALSE; 
           }
        }
        public function auth_session() {
           if($this->session->has_userdata('user'))
           {
             return TRUE;
           }  else {
               return FALSE; 
           }
        }
        
        public function logout() {
            
            $this->session->unset_userdata('user');
            $this->session->sess_destroy();
        }
        
        
              /*
     * function to status bus
     */
    function status_user($user_id,$status)
    {  
        $this->db->set('user_status', $status, FALSE);
       $this->db->where('id',$user_id);
       $response = $this->db->update('User');
        if($response)
        {
            return "User Status updated successfully";
        }
        else
        {
            return "Error occuring while updating User Status";
        }
    }
}
